/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Value object for CollaborativeSession.
 *
 * @lomboz generated
 */
public class CollaborativeSessionFileValue
   extends  
java.lang.Object 
   implements java.io.Serializable 
{
   private java.lang.Integer collaborativeSessionID;
   private boolean collaborativeSessionIDHasBeenSet = false;
   private java.lang.String opmModelFile;
   private boolean opmModelFileHasBeenSet = false;

   private java.lang.Integer pk;

   public CollaborativeSessionFileValue()
   {
   }

   public CollaborativeSessionFileValue( java.lang.Integer collaborativeSessionID,java.lang.String opmModelFile )
   {
	  this.collaborativeSessionID = collaborativeSessionID;
	  collaborativeSessionIDHasBeenSet = true;
	  this.opmModelFile = opmModelFile;
	  opmModelFileHasBeenSet = true;
	  pk = this.getCollaborativeSessionID();
   }

   //
   public CollaborativeSessionFileValue( CollaborativeSessionFileValue otherValue )
   {
	  this.collaborativeSessionID = otherValue.collaborativeSessionID;
	  collaborativeSessionIDHasBeenSet = true;
	  this.opmModelFile = otherValue.opmModelFile;
	  opmModelFileHasBeenSet = true;

	  pk = this.getCollaborativeSessionID();
   }

   public java.lang.Integer getPrimaryKey()
   {
	  return pk;
   }

   public void setPrimaryKey( java.lang.Integer pk )
   {
      // it's also nice to update PK object - just in case
      // somebody would ask for it later...
      this.pk = pk;
	  setCollaborativeSessionID( pk );
   }

   public java.lang.Integer getCollaborativeSessionID()
   {
	  return this.collaborativeSessionID;
   }

   public void setCollaborativeSessionID( java.lang.Integer collaborativeSessionID )
   {
	  this.collaborativeSessionID = collaborativeSessionID;
	  collaborativeSessionIDHasBeenSet = true;

		  pk = collaborativeSessionID;
   }

   public boolean collaborativeSessionIDHasBeenSet(){
	  return collaborativeSessionIDHasBeenSet;
   }
   public java.lang.String getOpmModelFile()
   {
	  return this.opmModelFile;
   }

   public void setOpmModelFile( java.lang.String opmModelFile )
   {
	  this.opmModelFile = opmModelFile;
	  opmModelFileHasBeenSet = true;

   }

   public boolean opmModelFileHasBeenSet(){
	  return opmModelFileHasBeenSet;
   }

   public String toString()
   {
	  StringBuffer str = new StringBuffer("{");

	  str.append("collaborativeSessionID=" + getCollaborativeSessionID() + " " + "opmModelFile=" + getOpmModelFile());
	  str.append('}');

	  return(str.toString());
   }

   /**
    * A Value Object has an identity if the attributes making its Primary Key have all been set. An object without identity is never equal to any other object.
    *
    * @return true if this instance has an identity.
    */
   protected boolean hasIdentity()
   {
	  return collaborativeSessionIDHasBeenSet;
   }

   public boolean equals(Object other)
   {
      if (this == other)
         return true;
	  if ( ! hasIdentity() ) return false;
	  if (other instanceof CollaborativeSessionFileValue)
	  {
		 CollaborativeSessionFileValue that = (CollaborativeSessionFileValue) other;
		 if ( ! that.hasIdentity() ) return false;
		 boolean lEquals = true;
		 if( this.collaborativeSessionID == null )
		 {
			lEquals = lEquals && ( that.collaborativeSessionID == null );
		 }
		 else
		 {
			lEquals = lEquals && this.collaborativeSessionID.equals( that.collaborativeSessionID );
		 }

		 lEquals = lEquals && isIdentical(that);

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public boolean isIdentical(Object other)
   {
	  if (other instanceof CollaborativeSessionFileValue)
	  {
		 CollaborativeSessionFileValue that = (CollaborativeSessionFileValue) other;
		 boolean lEquals = true;
		 if( this.opmModelFile == null )
		 {
			lEquals = lEquals && ( that.opmModelFile == null );
		 }
		 else
		 {
			lEquals = lEquals && this.opmModelFile.equals( that.opmModelFile );
		 }

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public int hashCode(){
	  int result = 17;
      result = 37*result + ((this.collaborativeSessionID != null) ? this.collaborativeSessionID.hashCode() : 0);

      result = 37*result + ((this.opmModelFile != null) ? this.opmModelFile.hashCode() : 0);

	  return result;
   }

}
