/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.session;

/**
 * Session layer for CollaborativeSessionAccess.
 * @lomboz generated
 */
public class CollaborativeSessionAccessSession
   extends org.objectprocess.session.CollaborativeSessionAccessBean
   implements javax.ejb.SessionBean
{
   public void ejbActivate() 
   {
   }

   public void ejbPassivate() 
   {
   }

   public void setSessionContext(javax.ejb.SessionContext ctx) 
   {
      super.setSessionContext(ctx);
   }

   public void unsetSessionContext() 
   {
      super.unsetSessionContext();
   }

   public void ejbRemove() 
   {
   }

}
