/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.session;

/**
 * Home interface for CollaborativeSessionAccess.
 * @lomboz generated
 */
public interface CollaborativeSessionAccessHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CollaborativeSessionAccess";
   public static final String JNDI_NAME="CollaborativeSessionAccessBean";

   public org.objectprocess.session.CollaborativeSessionAccess create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
