/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.session;

/**
 * Local home interface for CollaborativeSessionAccess.
 * @lomboz generated
 */
public interface CollaborativeSessionAccessLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CollaborativeSessionAccessLocal";
   public static final String JNDI_NAME="CollaborativeSessionAccessLocal";

   public org.objectprocess.session.CollaborativeSessionAccessLocal create()
      throws javax.ejb.CreateException;

}
