/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.session;

/**
 * Home interface for OpmModelAccess.
 * @lomboz generated
 */
public interface OpmModelAccessHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OpmModelAccess";
   public static final String JNDI_NAME="OpmModelAccessBean";

   public org.objectprocess.session.OpmModelAccess create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
