/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.session;

/**
 * Local home interface for OpmModelAccess.
 * @lomboz generated
 */
public interface OpmModelAccessLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OpmModelAccessLocal";
   public static final String JNDI_NAME="OpmModelAccessLocal";

   public org.objectprocess.session.OpmModelAccessLocal create()
      throws javax.ejb.CreateException;

}
