/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.session;

/**
 * Home interface for UserAccess.
 * @lomboz generated
 */
public interface UserAccessHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/UserAccess";
   public static final String JNDI_NAME="UserAccessBean";

   public org.objectprocess.session.UserAccess create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
