/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.session;

/**
 * Local home interface for WorkgroupAccess.
 * @lomboz generated
 */
public interface WorkgroupAccessLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/WorkgroupAccessLocal";
   public static final String JNDI_NAME="WorkgroupAccessLocal";

   public org.objectprocess.session.WorkgroupAccessLocal create()
      throws javax.ejb.CreateException;

}
