CREATE TABLE `user` (
  `USERID` varchar(32) NOT NULL,
  `LOGINNAME` varchar(20) NOT NULL,
  `FIRSTNAME` varchar(20) NOT NULL,
  `LASTNAME` varchar(20) NOT NULL,
  `PASSWORD` varchar(20) NOT NULL,
  `EMAIL` varchar(30),
  `ENABLED` tinyint(1) NOT NULL DEFAULT 1,
  `LOGGEDIN` tinyint(1) NOT NULL DEFAULT 0,
  `LASTLOGINTIME` datetime NOT NULL,
  `DESCRIPTION` blob,
  `ADMINISTRATOR` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY  (`USERID`),
  UNIQUE KEY `LOGINNAME` (`LOGINNAME`)
) TYPE=InnoDB; 

CREATE TABLE `workgroup` (
  `WORKGROUPID` varchar(32) NOT NULL,
  `WORKGROUPNAME` varchar(20) NOT NULL,
  `ENABLED` tinyint(1) NOT NULL DEFAULT 1,
  `CREATIONTIME` datetime NOT NULL,
  `DESCRIPTION` blob,
  PRIMARY KEY  (`WORKGROUPID`),
  UNIQUE KEY `WORKGROUPNAME` (`WORKGROUPNAME`)
) TYPE=InnoDB; 

CREATE TABLE `opmmodel` (
  `OPMMODELID` varchar(32) NOT NULL,
  `OPMMODELNAME` varchar(20) NOT NULL,
  `WORKGROUPID` varchar(32) NOT NULL,
  `ENABLED` tinyint(1) NOT NULL DEFAULT 1,
  `CREATIONTIME` datetime NOT NULL,
  `DESCRIPTION` blob,
  `TOTALCOLLABORATIVETIME` bigint(20) NOT NULL DEFAULT 0,
  PRIMARY KEY  (`OPMMODELID`),
  UNIQUE KEY `OPMMODELNAME` (`OPMMODELNAME`),
  KEY `WORKGROUPID_IND` (`WORKGROUPID`),
  CONSTRAINT `FK_OPMMODEL_WORKGROUPID` FOREIGN KEY (`WORKGROUPID`) REFERENCES `workgroup` (`WORKGROUPID`)
) TYPE=InnoDB; 

CREATE TABLE `revision` (
  `REVISIONID` varchar(32) NOT NULL,
  `OPMMODELID` varchar(32) NOT NULL,
  `OPMMODELFILE` mediumblob NOT NULL,
  `ENABLED` tinyint(1) NOT NULL DEFAULT 1,
  `MAJORREVISION` int(15) NOT NULL,
  `MINORREVISION` int(15) NOT NULL,
  `BUILD` int(15) NOT NULL,
  `CREATIONTIME` datetime NOT NULL ,
  `COMITTERID` varchar(32) NOT NULL,
  `DESCRIPTION` blob NOT NULL,
   PRIMARY KEY(`REVISIONID`),
   UNIQUE KEY `REVISION` (`OPMMODELID`,`REVISIONID`),
   KEY `OPMMODELID_IND` (`OPMMODELID`),
   KEY `COMITTERID_IND` (`COMITTERID`),
   CONSTRAINT `FK_OPMMODELID` FOREIGN KEY (`OPMMODELID`) REFERENCES `opmmodel` (`OPMMODELID`),
   CONSTRAINT `FK_COMMITER` FOREIGN KEY (`COMITTERID`) REFERENCES `user` (`USERID`)
) TYPE=InnoDB; 

CREATE TABLE `collaborative_session` (
  `SESSIONID` varchar(32) NOT NULL,
  `OPMMODELID` varchar(32) NOT NULL,
  `REVISIONID` varchar(32) NOT NULL,
  `SESSIONNAME` varchar(20) NOT NULL,
  `ENABLED` tinyint(1) NOT NULL DEFAULT 1,
  `DONE` tinyint(1) NOT NULL DEFAULT 0,
  `DIRTY` tinyint(1)  NOT NULL DEFAULT 0,
  `CREATIONTIME` datetime NOT NULL,
  `DESCRIPTION` blob,
  `TOKENTIMEOUT` int(15) NOT NULL DEFAULT 6000,
  `LASTUPDATE` datetime NOT NULL,
  `USERTIMEOUT` int(15) NOT NULL DEFAULT 6000,
  `TOKENHOLDERID` varchar(32) NOT NULL,
  `OPMMODELFILE` mediumblob,
  PRIMARY KEY  (`SESSIONID`),
  UNIQUE KEY `SESSIONNAME` (`SESSIONNAME`),
  KEY `OPMMODELID_IND` (`OPMMODELID`),
  KEY `TOKENHOLDERID_IND` (`TOKENHOLDERID`),
  KEY `REVISIONID_IND` (`REVISIONID`),
  CONSTRAINT `FK_COLLABORATIVE_SESSION_OPMMODELID` FOREIGN KEY (`OPMMODELID`) REFERENCES `opmmodel` (`OPMMODELID`),
  CONSTRAINT `FK_COLLABORATIVE_SESSION_TOKENHOLDERID` FOREIGN KEY (`TOKENHOLDERID`) REFERENCES `user` (`USERID`),
  CONSTRAINT `FK_COLLABORATIVE_SESSION_REVISIONID` FOREIGN KEY (`REVISIONID`) REFERENCES `revision` (`REVISIONID`)
) TYPE=InnoDB; 

CREATE TABLE `workgroup_permissions` (
  `WORKGROUPID` varchar(32) NOT NULL,
  `USERID` varchar(32) NOT NULL,
  `JOINTIME` datetime NOT NULL,
  `ACCESSCONTROL` bigint(20) NOT NULL,
  PRIMARY KEY  (`WORKGROUPID`,`USERID`),
  KEY `USERID_IND` (`USERID`),
  KEY `WORKGROUPID_IND` (`WORKGROUPID`),
  CONSTRAINT `FK_WORKGROUP_PERMISSIONS_USERID` FOREIGN KEY (`USERID`) REFERENCES `user` (`USERID`),
  CONSTRAINT `FK_WORKGROUP_PERMISSIONS_WORKGROUPID` FOREIGN KEY (`WORKGROUPID`) REFERENCES `workgroup` (`WORKGROUPID`)
) TYPE=InnoDB; 

CREATE TABLE `session_permissions` (
  `SESSIONID` varchar(32) NOT NULL,
  `USERID` varchar(32) NOT NULL,
  `JOINTIME` datetime NOT NULL,
  `ACCESSCONTROL` bigint(20) NOT NULL,
  PRIMARY KEY  (`SESSIONID`,`USERID`),
  KEY `USERID_IND` (`USERID`),
  KEY `SESSIONID_IND` (`SESSIONID`),
  CONSTRAINT `FK_SESSION_PERMISSIONS_USERID` FOREIGN KEY (`USERID`) REFERENCES `user` (`USERID`),
  CONSTRAINT `FK_SESSION_PERMISSIONS_SESSIONID` FOREIGN KEY (`SESSIONID`) REFERENCES `collaborative_session` (`SESSIONID`)
) TYPE=InnoDB; 

CREATE TABLE `opmmodel_permissions` (
  `OPMMODELID` varchar(32) NOT NULL,
  `USERID` varchar(32) NOT NULL,
  `JOINTIME` datetime NOT NULL,
  `ACCESSCONTROL` bigint(20) NOT NULL,
  PRIMARY KEY  (`OPMMODELID`,`USERID`),
  KEY `USERID_IND` (`USERID`),
  KEY `OPMMODELID_IND` (`OPMMODELID`),
  CONSTRAINT `FK_OPMMODEL_PERMISSIONS_USERID` FOREIGN KEY (`USERID`) REFERENCES `user` (`USERID`),
  CONSTRAINT `FK_OPMMODEL_PERMISSIONS_OPMMODELID` FOREIGN KEY (`OPMMODELID`) REFERENCES `opmmodel` (`OPMMODELID`)
) TYPE=InnoDB; 
