/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Value object for CollaborativeSession.
 * 
 * @lomboz generated
 */
public class CollaborativeSessionFileValue extends java.lang.Object implements
		java.io.Serializable {
	 

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 
	 */
	 

	private java.lang.Integer collaborativeSessionID;

	private boolean collaborativeSessionIDHasBeenSet = false;

	private java.lang.String opmModelFile;

	private boolean opmModelFileHasBeenSet = false;

	private java.lang.Integer pk;

	public CollaborativeSessionFileValue() {
	}

	public CollaborativeSessionFileValue(
			java.lang.Integer collaborativeSessionID,
			java.lang.String opmModelFile) {
		this.collaborativeSessionID = collaborativeSessionID;
		this.collaborativeSessionIDHasBeenSet = true;
		this.opmModelFile = opmModelFile;
		this.opmModelFileHasBeenSet = true;
		this.pk = this.getCollaborativeSessionID();
	}

	//
	public CollaborativeSessionFileValue(
			CollaborativeSessionFileValue otherValue) {
		this.collaborativeSessionID = otherValue.collaborativeSessionID;
		this.collaborativeSessionIDHasBeenSet = true;
		this.opmModelFile = otherValue.opmModelFile;
		this.opmModelFileHasBeenSet = true;

		this.pk = this.getCollaborativeSessionID();
	}

	public java.lang.Integer getPrimaryKey() {
		return this.pk;
	}

	public void setPrimaryKey(java.lang.Integer pk) {
		// it's also nice to update PK object - just in case
		// somebody would ask for it later...
		this.pk = pk;
		this.setCollaborativeSessionID(pk);
	}

	public java.lang.Integer getCollaborativeSessionID() {
		return this.collaborativeSessionID;
	}

	public void setCollaborativeSessionID(
			java.lang.Integer collaborativeSessionID) {
		this.collaborativeSessionID = collaborativeSessionID;
		this.collaborativeSessionIDHasBeenSet = true;

		this.pk = collaborativeSessionID;
	}

	public boolean collaborativeSessionIDHasBeenSet() {
		return this.collaborativeSessionIDHasBeenSet;
	}

	public java.lang.String getOpmModelFile() {
		return this.opmModelFile;
	}

	public void setOpmModelFile(java.lang.String opmModelFile) {
		this.opmModelFile = opmModelFile;
		this.opmModelFileHasBeenSet = true;

	}

	public boolean opmModelFileHasBeenSet() {
		return this.opmModelFileHasBeenSet;
	}

	public String toString() {
		StringBuffer str = new StringBuffer("{");

		str.append("collaborativeSessionID=" + this.getCollaborativeSessionID()
				+ " " + "opmModelFile=" + this.getOpmModelFile());
		str.append('}');

		return (str.toString());
	}

	/**
	 * A Value Object has an identity if the attributes making its Primary Key
	 * have all been set. An object without identity is never equal to any other
	 * object.
	 * 
	 * @return true if this instance has an identity.
	 */
	protected boolean hasIdentity() {
		return this.collaborativeSessionIDHasBeenSet;
	}

	public boolean equals(Object other) {
		if (this == other) {
			return true;
		}
		if (!this.hasIdentity()) {
			return false;
		}
		if (other instanceof CollaborativeSessionFileValue) {
			CollaborativeSessionFileValue that = (CollaborativeSessionFileValue) other;
			if (!that.hasIdentity()) {
				return false;
			}
			boolean lEquals = true;
			if (this.collaborativeSessionID == null) {
				lEquals = lEquals && (that.collaborativeSessionID == null);
			} else {
				lEquals = lEquals
						&& this.collaborativeSessionID
								.equals(that.collaborativeSessionID);
			}

			lEquals = lEquals && this.isIdentical(that);

			return lEquals;
		} else {
			return false;
		}
	}

	public boolean isIdentical(Object other) {
		if (other instanceof CollaborativeSessionFileValue) {
			CollaborativeSessionFileValue that = (CollaborativeSessionFileValue) other;
			boolean lEquals = true;
			if (this.opmModelFile == null) {
				lEquals = lEquals && (that.opmModelFile == null);
			} else {
				lEquals = lEquals
						&& this.opmModelFile.equals(that.opmModelFile);
			}

			return lEquals;
		} else {
			return false;
		}
	}

	public int hashCode() {
		int result = 17;
		result = 37
				* result
				+ ((this.collaborativeSessionID != null) ? this.collaborativeSessionID
						.hashCode()
						: 0);

		result = 37
				* result
				+ ((this.opmModelFile != null) ? this.opmModelFile.hashCode()
						: 0);

		return result;
	}

}
