/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Primary key for CollaborativeSessionPermissions.
 * 
 * @lomboz generated
 */
public class CollaborativeSessionPermissionsPK extends java.lang.Object
		implements java.io.Serializable {
	/**
	 * 
	 */
	 

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * 
	 */
	private int _hashCode = 0;

	private StringBuffer _toStringValue = null;

	public java.lang.Integer collaborativeSessionID;

	public java.lang.Integer userID;

	public CollaborativeSessionPermissionsPK() {
	}

	public CollaborativeSessionPermissionsPK(
			java.lang.Integer collaborativeSessionID, java.lang.Integer userID) {
		this.collaborativeSessionID = collaborativeSessionID;
		this.userID = userID;
	}

	public java.lang.Integer getCollaborativeSessionID() {
		return this.collaborativeSessionID;
	}

	public java.lang.Integer getUserID() {
		return this.userID;
	}

	public void setCollaborativeSessionID(
			java.lang.Integer collaborativeSessionID) {
		this.collaborativeSessionID = collaborativeSessionID;
		this._hashCode = 0;
	}

	public void setUserID(java.lang.Integer userID) {
		this.userID = userID;
		this._hashCode = 0;
	}

	public int hashCode() {
		if (this._hashCode == 0) {
			if (this.collaborativeSessionID != null) {
				this._hashCode += this.collaborativeSessionID.hashCode();
			}
			if (this.userID != null) {
				this._hashCode += this.userID.hashCode();
			}
		}

		return this._hashCode;
	}

	public boolean equals(Object obj) {
		if (!(obj instanceof org.objectprocess.cmp.CollaborativeSessionPermissionsPK)) {
			return false;
		}

		org.objectprocess.cmp.CollaborativeSessionPermissionsPK pk = (org.objectprocess.cmp.CollaborativeSessionPermissionsPK) obj;
		boolean eq = true;

		if (obj == null) {
			eq = false;
		} else {
			if ((this.collaborativeSessionID == null)
					&& (((org.objectprocess.cmp.CollaborativeSessionPermissionsPK) obj)
							.getCollaborativeSessionID() == null)) {
				eq = true;
			} else {
				if ((this.collaborativeSessionID == null)
						|| (((org.objectprocess.cmp.CollaborativeSessionPermissionsPK) obj)
								.getCollaborativeSessionID() == null)) {
					eq = false;
				} else {
					eq = eq
							&& this.collaborativeSessionID
									.equals(pk.collaborativeSessionID);
				}
			}
			if ((this.userID == null)
					&& (((org.objectprocess.cmp.CollaborativeSessionPermissionsPK) obj)
							.getUserID() == null)) {
				eq = true;
			} else {
				if ((this.userID == null)
						|| (((org.objectprocess.cmp.CollaborativeSessionPermissionsPK) obj)
								.getUserID() == null)) {
					eq = false;
				} else {
					eq = eq && this.userID.equals(pk.userID);
				}
			}
		}

		return eq;
	}

	/**
	 * @return String representation of this pk in the form of
	 *         [.field1.field2.field3].
	 */
	public String toString() {
		if (this._toStringValue == null) {
			this._toStringValue = new StringBuffer("[.");
			this._toStringValue.append(this.collaborativeSessionID).append('.');
			this._toStringValue.append(this.userID).append('.');
			this._toStringValue.append(']');
		}

		return this._toStringValue.toString();
	}

}
