/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Primary key for CollaborativeSessionPermissions.
 * @lomboz generated
 */
public class CollaborativeSessionPermissionsPK
   extends java.lang.Object
   implements java.io.Serializable
{
   private int _hashCode = 0;
   private StringBuffer _toStringValue = null;

   public java.lang.Integer collaborativeSessionID;
   public java.lang.Integer userID;

   public CollaborativeSessionPermissionsPK()
   {
   }

   public CollaborativeSessionPermissionsPK( java.lang.Integer collaborativeSessionID,java.lang.Integer userID )
   {
      this.collaborativeSessionID = collaborativeSessionID;
      this.userID = userID;
   }

   public java.lang.Integer getCollaborativeSessionID()
   {
      return collaborativeSessionID;
   }
   public java.lang.Integer getUserID()
   {
      return userID;
   }

   public void setCollaborativeSessionID(java.lang.Integer collaborativeSessionID)
   {
      this.collaborativeSessionID = collaborativeSessionID;
      _hashCode = 0;
   }
   public void setUserID(java.lang.Integer userID)
   {
      this.userID = userID;
      _hashCode = 0;
   }

   public int hashCode()
   {
      if( _hashCode == 0 )
      {
         if (this.collaborativeSessionID != null) _hashCode += this.collaborativeSessionID.hashCode();
         if (this.userID != null) _hashCode += this.userID.hashCode();
      }

      return _hashCode;
   }

   public boolean equals(Object obj)
   {
      if( !(obj instanceof org.objectprocess.cmp.CollaborativeSessionPermissionsPK) )
         return false;

      org.objectprocess.cmp.CollaborativeSessionPermissionsPK pk = (org.objectprocess.cmp.CollaborativeSessionPermissionsPK)obj;
      boolean eq = true;

      if( obj == null )
      {
         eq = false;
      }
      else
      {
         if( this.collaborativeSessionID == null && ((org.objectprocess.cmp.CollaborativeSessionPermissionsPK)obj).getCollaborativeSessionID() == null )
         {
            eq = true;
         }
         else
         {
            if( this.collaborativeSessionID == null || ((org.objectprocess.cmp.CollaborativeSessionPermissionsPK)obj).getCollaborativeSessionID() == null )
            {
               eq = false;
            }
            else
            {
               eq = eq && this.collaborativeSessionID.equals( pk.collaborativeSessionID );
            }
         }
         if( this.userID == null && ((org.objectprocess.cmp.CollaborativeSessionPermissionsPK)obj).getUserID() == null )
         {
            eq = true;
         }
         else
         {
            if( this.userID == null || ((org.objectprocess.cmp.CollaborativeSessionPermissionsPK)obj).getUserID() == null )
            {
               eq = false;
            }
            else
            {
               eq = eq && this.userID.equals( pk.userID );
            }
         }
      }

      return eq;
   }

   /** @return String representation of this pk in the form of [.field1.field2.field3]. */
   public String toString()
   {
      if( _toStringValue == null )
      {
         _toStringValue = new StringBuffer("[.");
         _toStringValue.append(this.collaborativeSessionID).append('.');
         _toStringValue.append(this.userID).append('.');
         _toStringValue.append(']');
      }

      return _toStringValue.toString();
   }

}
