/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Local interface for CollaborativeSessionPermissions.
 * @lomboz generated
 */
public interface CollaborativeSessionPermissionsLocal
   extends javax.ejb.EJBLocalObject
{

   public org.objectprocess.cmp.CollaborativeSessionLocal getCollaborativeSession(  ) ;

   public void setCollaborativeSession( org.objectprocess.cmp.CollaborativeSessionLocal CollaborativeSession ) ;

   public org.objectprocess.cmp.UserLocal getUser(  ) ;

   public void setUser( org.objectprocess.cmp.UserLocal user ) ;

   /**
    * Returns the collaborativeSessionID
    * @return the collaborativeSessionID
    */
   public java.lang.String getCollaborativeSessionID(  ) ;

   /**
    * Sets the collaborativeSessionID
    * @param java.lang.Integer the new collaborativeSessionID value
    */
   public void setCollaborativeSessionID( java.lang.String collaborativeSessionID ) ;

   /**
    * Returns the userID
    * @return the userID
    */
   public java.lang.String getUserID(  ) ;

   /**
    * Sets the userID
    * @param java.lang.Integer the new userID value
    */
   public void setUserID( java.lang.String userID ) ;

   /**
    * Returns the joinTime
    * @return the joinTime
    */
   public java.util.Date getJoinTime(  ) ;

   /**
    * Sets the joinTime
    * @param java.util.Date the new joinTime value
    */
   public void setJoinTime( java.util.Date joinTime ) ;

   /**
    * Returns the accessControl
    * @return the accessControl
    */
   public java.lang.Integer getAccessControl(  ) ;

   /**
    * Sets the accessControl
    * @param java.lang.Integer the new accessControl value
    */
   public void setAccessControl( java.lang.Integer accessControl ) ;

   public void setCollaborativeSessionPermissions( org.objectprocess.cmp.EditableCollaborativeSessionPermissionsValue editableCollaborativeSessionPermissionsValue ) ;

   public org.objectprocess.cmp.EnhancedCollaborativeSessionPermissionsValue getEnhancedCollaborativeSessionPermissionsValue(  ) ;

   public org.objectprocess.cmp.Enhanced2CollaborativeSessionPermissionsValue getEnhanced2CollaborativeSessionPermissionsValue(  ) ;

   public org.objectprocess.cmp.CollaborativeSessionPermissionsValue getCollaborativeSessionPermissionsValue(  ) ;

   public org.objectprocess.cmp.EditableCollaborativeSessionPermissionsValue getEditableCollaborativeSessionPermissionsValue(  ) ;

}
