/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Local home interface for CollaborativeSessionPermissions.
 * @lomboz generated
 */
public interface CollaborativeSessionPermissionsLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CollaborativeSessionPermissionsLocal";
   public static final String JNDI_NAME="CollaborativeSessionPermissionsLocal";

   public org.objectprocess.cmp.CollaborativeSessionPermissionsLocal create(org.objectprocess.cmp.EditableCollaborativeSessionPermissionsValue editableCollaborativeSessionPermissionsValue)
      throws javax.ejb.CreateException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public org.objectprocess.cmp.CollaborativeSessionPermissionsLocal findByPrimaryKey(org.objectprocess.cmp.CollaborativeSessionPermissionsPK pk)
      throws javax.ejb.FinderException;

}
