/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Local home interface for CollaborativeSession.
 * @lomboz generated
 */
public interface CollaborativeSessionLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CollaborativeSessionLocal";
   public static final String JNDI_NAME="CollaborativeSessionLocal";

   public org.objectprocess.cmp.CollaborativeSessionLocal create(org.objectprocess.cmp.EditableCollaborativeSessionValue editableCollaborativeSessionValue)
      throws javax.ejb.CreateException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public java.util.Collection findByCollaborativeSessionName(java.lang.String collaborativeSession)
      throws javax.ejb.FinderException;

   public org.objectprocess.cmp.CollaborativeSessionLocal findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException;

}
