/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Home interface for CollaborativeSession.
 * @lomboz generated
 */
public interface CollaborativeSessionHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CollaborativeSession";
   public static final String JNDI_NAME="CollaborativeSessionBean";

   public org.objectprocess.cmp.CollaborativeSession create(org.objectprocess.cmp.EditableCollaborativeSessionValue editableCollaborativeSessionValue)
      throws javax.ejb.CreateException,java.rmi.RemoteException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public java.util.Collection findByCollaborativeSessionName(java.lang.String collaborativeSession)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public org.objectprocess.cmp.CollaborativeSession findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
