/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Home interface for CollaborativeSessionPermissions.
 * @lomboz generated
 */
public interface CollaborativeSessionPermissionsHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/CollaborativeSessionPermissions";
   public static final String JNDI_NAME="CollaborativeSessionPermissionsBean";

   public org.objectprocess.cmp.CollaborativeSessionPermissions create(org.objectprocess.cmp.EditableCollaborativeSessionPermissionsValue editableCollaborativeSessionPermissionsValue)
      throws javax.ejb.CreateException,java.rmi.RemoteException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public org.objectprocess.cmp.CollaborativeSessionPermissions findByPrimaryKey(org.objectprocess.cmp.CollaborativeSessionPermissionsPK pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
