/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Local interface for CollaborativeSession.
 * @lomboz generated
 */
public interface CollaborativeSessionLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Returns a <code>Collection</code> of <code>CollaborativeSessionPermissionsLocal</code> related to the collaborative session.
    * @return a <code>Collection</code> of related <code>CollaborativeSessionPermissionsLocal</code>.
    */
   public java.util.Collection getCollaborativeSessionPermissions(  ) ;

   public void setCollaborativeSessionPermissions( java.util.Collection collaborativeSessionPermissions ) ;

   /**
    * Returns the <code>OpmModelLocal</code> the collaborative session is based on.
    * @return the <code>OpmModelLocal</code>.
    */
   public org.objectprocess.cmp.OpmModelLocal getOpmModel(  ) ;

   public void setOpmModel( org.objectprocess.cmp.OpmModelLocal OpmModel ) ;

   /**
    * Returns the collaborative session's id.
    * @return the collaborative session's id.
    */
   public java.lang.String getCollaborativeSessionID(  ) ;

   /**
    * Sets the collaborative session's id
    * @param collaborativeSessionID the new collaborative session's id value
    */
   public void setCollaborativeSessionID( java.lang.String collaborativeSessionID ) ;

   /**
    * Returns the collaborative session's name.
    * @return the collaborative session's name.
    */
   public java.lang.String getCollaborativeSessionName(  ) ;

   /**
    * Sets the collaborative session's name.
    * @param collaborativeSessionName the new collaborative session's name value
    */
   public void setCollaborativeSessionName( java.lang.String collaborativeSessionName ) ;

   /**
    * Returns the collaborative session's <code>enabled</code> flag value.
    * @return the collaborative session's <code>enabled</code> flag value.
    */
   public java.lang.Boolean getEnabled(  ) ;

   /**
    * Sets the the collaborative session's <code>enabled</code> flag value.
    * @param enabled the new <code>enabled</code> flag value.
    */
   public void setEnabled( java.lang.Boolean enabled ) ;

   /**
    * Returns the collaborative session's <code>dirty</code> flag value.
    * @return the collaborative session's <code>dirty</code> flag value.
    */
   public java.lang.Boolean getDirty(  ) ;

   /**
    * Sets the collaborative session's <code>dirty</code> flag value.
    * @param dirty the new <code>dirty</code> flag value.
    */
   public void setDirty( java.lang.Boolean dirty ) ;

   /**
    * Returns the collaborative session's <code>terminated</code> flag value. The <code>terminated</code> flag is set to <code>true</code> once the session is commited into a new revision.
    * @return the collaborative session's <code>terminated</code> flag value.
    */
   public java.lang.Boolean getTerminated(  ) ;

   /**
    * Sets the collaborative session's <code>terminated</code> flag value.
    * @param terminated the new <code>terminated</code> value.
    */
   public void setTerminated( java.lang.Boolean terminated ) ;

   /**
    * Returns the time the collaborative session was created.
    * @return the time the collaborative session was created.
    */
   public java.util.Date getCreationTime(  ) ;

   /**
    * Sets the time for collaborative session creation, Initialized once, on <code>ejbCreate</code>.
    * @param CreationTime the new timestamp value.
    */
   public void setCreationTime( java.util.Date creationTime ) ;

   /**
    * Returns the collaborative session's description.
    * @return the collaborative session's description.
    */
   public java.lang.String getDescription(  ) ;

   /**
    * Sets the collaborative session's description.
    * @param description the new description value.
    */
   public void setDescription( java.lang.String description ) ;

   /**
    * Returns the last time the OPM model has been saved into the session.
    * @return the last time the OPM model has been saved into the session.
    */
   public java.util.Date getLastUpdate(  ) ;

   /**
    * Sets the last time the OPM model has been saved into the session.
    * @param lastUpdate the new lastUpdate value.
    */
   public void setLastUpdate( java.util.Date lastUpdate ) ;

   /**
    * Returns the id for the OPM model the session is based on.
    * @return the id for the OPM model the session is based on.
    */
   public java.lang.String getOpmModelID(  ) ;

   /**
    * Sets the id for the OPM model the session is based on.
    * @param opmModelID the new opmModelID value.
    */
   public void setOpmModelID( java.lang.String opmModelID ) ;

   /**
    * Returns the id for the OPM model revision the session is based on.
    * @return the revision id.
    */
   public java.lang.String getRevisionID(  ) ;

   /**
    * Sets the id for the OPM model revision the session is based on.
    * @param revision the new revision id value.
    */
   public void setRevisionID( java.lang.String revisionID ) ;

   /**
    * Returns the token timeout defined for the session. a client holding the session's token has to report to the server every <code>tokenTimeout</code> milliseconds. Failing to report within this time frame will transfer the token to the server.
    * @return the token timeout value.
    */
   public java.lang.Integer getTokenTimeout(  ) ;

   /**
    * Sets the token timeout defined for the session.
    * @param tokenTimeout the new tokenTimeout value.
    */
   public void setTokenTimeout( java.lang.Integer tokenTimeout ) ;

   /**
    * Returns the user timeout defined for the session.
    * @return the user timeout value.
    */
   public java.lang.Integer getUserTimeout(  ) ;

   /**
    * Sets the user timeout defined for the session.
    * @param userTimeout the new user timeout value.
    */
   public void setUserTimeout( java.lang.Integer userTimeout ) ;

   /**
    * Returns the id for the user currently holding the session token.
    * @return the token holder id.
    */
   public java.lang.String getTokenHolderID(  ) ;

   /**
    * Sets the id for the user currently holding the session token.
    * @param tokenHolderID the new token holder id value.
    */
   public void setTokenHolderID( java.lang.String tokenHolderID ) ;

   /**
    * Returns the OPX file currently stored in the session.
    * @return the opmModelFile
    */
   public java.lang.String getOpmModelFile(  ) ;

   /**
    * Sets the file currently stored in the session.
    * @param opmModelFile the new OPX file.
    */
   public void setOpmModelFile( java.lang.String opmModelFile ) ;

   public org.objectprocess.cmp.CollaborativeSessionValue getCollaborativeSessionValue(  ) ;

   public org.objectprocess.cmp.EnhancedCollaborativeSessionValue getEnhancedCollaborativeSessionValue(  ) ;

   public org.objectprocess.cmp.EditableCollaborativeSessionValue getEditableCollaborativeSessionValue(  ) ;

   public org.objectprocess.cmp.UpdatableCollaborativeSessionValue getUpdatableCollaborativeSessionValue(  ) ;

   public org.objectprocess.cmp.CollaborativeSessionFileValue getCollaborativeSessionFileValue(  ) ;

   public void setCollaborativeSessionFileValue( org.objectprocess.cmp.CollaborativeSessionFileValue collaborativeSessionFileValue ) ;

   public void setUpdatableCollaborativeSessionValue( org.objectprocess.cmp.UpdatableCollaborativeSessionValue updatableCollaborativeSessionValue ) ;

   public void setEditableCollaborativeSessionValue( org.objectprocess.cmp.EditableCollaborativeSessionValue editableCollaborativeSessionValue ) ;

}
