/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Primary key for CollaborativeSessionPermissions.
 * @lomboz generated
 */
public class CollaborativeSessionPermissionsPK
   extends java.lang.Object
   implements java.io.Serializable
{

   public java.lang.String collaborativeSessionID;
   public java.lang.String userID;

   public CollaborativeSessionPermissionsPK()
   {
   }

   public CollaborativeSessionPermissionsPK( java.lang.String collaborativeSessionID,java.lang.String userID )
   {
      this.collaborativeSessionID = collaborativeSessionID;
      this.userID = userID;
   }

   public java.lang.String getCollaborativeSessionID()
   {
      return collaborativeSessionID;
   }
   public java.lang.String getUserID()
   {
      return userID;
   }

   public void setCollaborativeSessionID(java.lang.String collaborativeSessionID)
   {
      this.collaborativeSessionID = collaborativeSessionID;
   }
   public void setUserID(java.lang.String userID)
   {
      this.userID = userID;
   }

   public int hashCode()
   {
      int _hashCode = 0;
         if (this.collaborativeSessionID != null) _hashCode += this.collaborativeSessionID.hashCode();
         if (this.userID != null) _hashCode += this.userID.hashCode();

      return _hashCode;
   }

   public boolean equals(Object obj)
   {
      if( !(obj instanceof org.objectprocess.cmp.CollaborativeSessionPermissionsPK) )
         return false;

      org.objectprocess.cmp.CollaborativeSessionPermissionsPK pk = (org.objectprocess.cmp.CollaborativeSessionPermissionsPK)obj;
      boolean eq = true;

      if( obj == null )
      {
         eq = false;
      }
      else
      {
         if( this.collaborativeSessionID != null )
         {
            eq = eq && this.collaborativeSessionID.equals( pk.getCollaborativeSessionID() );
         }
         else  // this.collaborativeSessionID == null
         {
            eq = eq && ( pk.getCollaborativeSessionID() == null );
         }
         if( this.userID != null )
         {
            eq = eq && this.userID.equals( pk.getUserID() );
         }
         else  // this.userID == null
         {
            eq = eq && ( pk.getUserID() == null );
         }
      }

      return eq;
   }

   /** @return String representation of this pk in the form of [.field1.field2.field3]. */
   public String toString()
   {
      StringBuffer toStringValue = new StringBuffer("[.");
         toStringValue.append(this.collaborativeSessionID).append('.');
         toStringValue.append(this.userID).append('.');
      toStringValue.append(']');
      return toStringValue.toString();
   }

}
