/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Remote interface for CollaborativeSessionPermissions.
 * @lomboz generated
 */
public interface CollaborativeSessionPermissions
   extends javax.ejb.EJBObject
{
   /**
    * Returns the collaborativeSessionID
    * @return the collaborativeSessionID
    */
   public java.lang.String getCollaborativeSessionID(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the collaborativeSessionID
    * @param java.lang.Integer the new collaborativeSessionID value
    */
   public void setCollaborativeSessionID( java.lang.String collaborativeSessionID )
      throws java.rmi.RemoteException;

   /**
    * Returns the userID
    * @return the userID
    */
   public java.lang.String getUserID(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the userID
    * @param java.lang.Integer the new userID value
    */
   public void setUserID( java.lang.String userID )
      throws java.rmi.RemoteException;

   /**
    * Returns the joinTime
    * @return the joinTime
    */
   public java.util.Date getJoinTime(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the joinTime
    * @param java.util.Date the new joinTime value
    */
   public void setJoinTime( java.util.Date joinTime )
      throws java.rmi.RemoteException;

   /**
    * Returns the accessControl
    * @return the accessControl
    */
   public java.lang.Integer getAccessControl(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the accessControl
    * @param java.lang.Integer the new accessControl value
    */
   public void setAccessControl( java.lang.Integer accessControl )
      throws java.rmi.RemoteException;

}
