/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Value object for CollaborativeSessionPermissions.
 *
 * @lomboz generated
 */
public class EnhancedCollaborativeSessionPermissionsValue
   extends java.lang.Object
   implements java.io.Serializable 
{
   private java.lang.String collaborativeSessionID;
   private boolean collaborativeSessionIDHasBeenSet = false;
   private java.lang.String userID;
   private boolean userIDHasBeenSet = false;
   private java.util.Date joinTime;
   private boolean joinTimeHasBeenSet = false;
   private java.lang.Integer accessControl;
   private boolean accessControlHasBeenSet = false;
   private org.objectprocess.cmp.CollaborativeSessionValue CollaborativeSession;
   private boolean CollaborativeSessionHasBeenSet = false;

   private org.objectprocess.cmp.CollaborativeSessionPermissionsPK pk;

   public EnhancedCollaborativeSessionPermissionsValue()
   {
	  pk = new org.objectprocess.cmp.CollaborativeSessionPermissionsPK();
   }

   public EnhancedCollaborativeSessionPermissionsValue( java.lang.String collaborativeSessionID,java.lang.String userID,java.util.Date joinTime,java.lang.Integer accessControl )
   {
	  this.collaborativeSessionID = collaborativeSessionID;
	  collaborativeSessionIDHasBeenSet = true;
	  this.userID = userID;
	  userIDHasBeenSet = true;
	  this.joinTime = joinTime;
	  joinTimeHasBeenSet = true;
	  this.accessControl = accessControl;
	  accessControlHasBeenSet = true;
	  pk = new org.objectprocess.cmp.CollaborativeSessionPermissionsPK(this.getCollaborativeSessionID(),this.getUserID());
   }

   //TODO Cloneable is better than this !
   public EnhancedCollaborativeSessionPermissionsValue( EnhancedCollaborativeSessionPermissionsValue otherValue )
   {
	  this.collaborativeSessionID = otherValue.collaborativeSessionID;
	  collaborativeSessionIDHasBeenSet = true;
	  this.userID = otherValue.userID;
	  userIDHasBeenSet = true;
	  this.joinTime = otherValue.joinTime;
	  joinTimeHasBeenSet = true;
	  this.accessControl = otherValue.accessControl;
	  accessControlHasBeenSet = true;
	// TODO Clone is better no ?
	  this.CollaborativeSession = otherValue.CollaborativeSession;
	  CollaborativeSessionHasBeenSet = true;

	  pk = new org.objectprocess.cmp.CollaborativeSessionPermissionsPK(this.getCollaborativeSessionID(),this.getUserID());
   }

   public org.objectprocess.cmp.CollaborativeSessionPermissionsPK getPrimaryKey()
   {
	  return pk;
   }

   public void setPrimaryKey( org.objectprocess.cmp.CollaborativeSessionPermissionsPK pk )
   {
      // it's also nice to update PK object - just in case
      // somebody would ask for it later...
      this.pk = pk;
	  setCollaborativeSessionID( pk.collaborativeSessionID );
	  setUserID( pk.userID );
   }

   public java.lang.String getCollaborativeSessionID()
   {
	  return this.collaborativeSessionID;
   }

   public void setCollaborativeSessionID( java.lang.String collaborativeSessionID )
   {
	  this.collaborativeSessionID = collaborativeSessionID;
	  collaborativeSessionIDHasBeenSet = true;

		 pk.setCollaborativeSessionID(collaborativeSessionID);
   }

   public boolean collaborativeSessionIDHasBeenSet(){
	  return collaborativeSessionIDHasBeenSet;
   }
   public java.lang.String getUserID()
   {
	  return this.userID;
   }

   public void setUserID( java.lang.String userID )
   {
	  this.userID = userID;
	  userIDHasBeenSet = true;

		 pk.setUserID(userID);
   }

   public boolean userIDHasBeenSet(){
	  return userIDHasBeenSet;
   }
   public java.util.Date getJoinTime()
   {
	  return this.joinTime;
   }

   public void setJoinTime( java.util.Date joinTime )
   {
	  this.joinTime = joinTime;
	  joinTimeHasBeenSet = true;

   }

   public boolean joinTimeHasBeenSet(){
	  return joinTimeHasBeenSet;
   }
   public java.lang.Integer getAccessControl()
   {
	  return this.accessControl;
   }

   public void setAccessControl( java.lang.Integer accessControl )
   {
	  this.accessControl = accessControl;
	  accessControlHasBeenSet = true;

   }

   public boolean accessControlHasBeenSet(){
	  return accessControlHasBeenSet;
   }

   public org.objectprocess.cmp.CollaborativeSessionValue getCollaborativeSession()
   {
	  return this.CollaborativeSession;
   }
   public void setCollaborativeSession( org.objectprocess.cmp.CollaborativeSessionValue CollaborativeSession )
   {
	  this.CollaborativeSession = CollaborativeSession;
	  CollaborativeSessionHasBeenSet = true;
   }

   public String toString()
   {
	  StringBuffer str = new StringBuffer("{");

	  str.append("collaborativeSessionID=" + getCollaborativeSessionID() + " " + "userID=" + getUserID() + " " + "joinTime=" + getJoinTime() + " " + "accessControl=" + getAccessControl());
	  str.append('}');

	  return(str.toString());
   }

   /**
    * A Value Object has an identity if the attributes making its Primary Key have all been set. An object without identity is never equal to any other object.
    *
    * @return true if this instance has an identity.
    */
   protected boolean hasIdentity()
   {
	  boolean ret = true;
	  ret = ret && collaborativeSessionIDHasBeenSet;
	  ret = ret && userIDHasBeenSet;
	  return ret;
   }

   public boolean equals(Object other)
   {
      if (this == other)
         return true;
	  if ( ! hasIdentity() ) return false;
	  if (other instanceof EnhancedCollaborativeSessionPermissionsValue)
	  {
		 EnhancedCollaborativeSessionPermissionsValue that = (EnhancedCollaborativeSessionPermissionsValue) other;
		 if ( ! that.hasIdentity() ) return false;
		 boolean lEquals = true;
		 if( this.collaborativeSessionID == null )
		 {
			lEquals = lEquals && ( that.collaborativeSessionID == null );
		 }
		 else
		 {
			lEquals = lEquals && this.collaborativeSessionID.equals( that.collaborativeSessionID );
		 }
		 if( this.userID == null )
		 {
			lEquals = lEquals && ( that.userID == null );
		 }
		 else
		 {
			lEquals = lEquals && this.userID.equals( that.userID );
		 }

		 lEquals = lEquals && isIdentical(that);

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public boolean isIdentical(Object other)
   {
	  if (other instanceof EnhancedCollaborativeSessionPermissionsValue)
	  {
		 EnhancedCollaborativeSessionPermissionsValue that = (EnhancedCollaborativeSessionPermissionsValue) other;
		 boolean lEquals = true;
		 if( this.joinTime == null )
		 {
			lEquals = lEquals && ( that.joinTime == null );
		 }
		 else
		 {
			lEquals = lEquals && this.joinTime.equals( that.joinTime );
		 }
		 if( this.accessControl == null )
		 {
			lEquals = lEquals && ( that.accessControl == null );
		 }
		 else
		 {
			lEquals = lEquals && this.accessControl.equals( that.accessControl );
		 }
		 if( this.CollaborativeSession == null )
		 {
			lEquals = lEquals && ( that.CollaborativeSession == null );
		 }
		 else
		 {
			lEquals = lEquals && this.CollaborativeSession.equals( that.CollaborativeSession );
		 }

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public int hashCode(){
	  int result = 17;
      result = 37*result + ((this.collaborativeSessionID != null) ? this.collaborativeSessionID.hashCode() : 0);

      result = 37*result + ((this.userID != null) ? this.userID.hashCode() : 0);

      result = 37*result + ((this.joinTime != null) ? this.joinTime.hashCode() : 0);

      result = 37*result + ((this.accessControl != null) ? this.accessControl.hashCode() : 0);

	  result = 37*result + ((this.CollaborativeSession != null) ? this.CollaborativeSession.hashCode() : 0);
	  return result;
   }

}
