/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Value object for OpmModel.
 *
 * @lomboz generated
 */
public class EnhancedOpmModelValue
   extends java.lang.Object
   implements java.io.Serializable 
{
   private java.lang.String opmModelID;
   private boolean opmModelIDHasBeenSet = false;
   private java.lang.String opmModelName;
   private boolean opmModelNameHasBeenSet = false;
   private java.lang.Boolean enabled;
   private boolean enabledHasBeenSet = false;
   private java.util.Date creationTime;
   private boolean creationTimeHasBeenSet = false;
   private java.lang.String description;
   private boolean descriptionHasBeenSet = false;
   private java.lang.String workgroupID;
   private boolean workgroupIDHasBeenSet = false;
   private java.lang.Integer totalCollaborativeTime;
   private boolean totalCollaborativeTimeHasBeenSet = false;
   private java.util.Collection OpmModelsPermissions = new java.util.ArrayList();

   private java.lang.String pk;

   public EnhancedOpmModelValue()
   {
   }

   public EnhancedOpmModelValue( java.lang.String opmModelID,java.lang.String opmModelName,java.lang.Boolean enabled,java.util.Date creationTime,java.lang.String description,java.lang.String workgroupID,java.lang.Integer totalCollaborativeTime )
   {
	  this.opmModelID = opmModelID;
	  opmModelIDHasBeenSet = true;
	  this.opmModelName = opmModelName;
	  opmModelNameHasBeenSet = true;
	  this.enabled = enabled;
	  enabledHasBeenSet = true;
	  this.creationTime = creationTime;
	  creationTimeHasBeenSet = true;
	  this.description = description;
	  descriptionHasBeenSet = true;
	  this.workgroupID = workgroupID;
	  workgroupIDHasBeenSet = true;
	  this.totalCollaborativeTime = totalCollaborativeTime;
	  totalCollaborativeTimeHasBeenSet = true;
	  pk = this.getOpmModelID();
   }

   //TODO Cloneable is better than this !
   public EnhancedOpmModelValue( EnhancedOpmModelValue otherValue )
   {
	  this.opmModelID = otherValue.opmModelID;
	  opmModelIDHasBeenSet = true;
	  this.opmModelName = otherValue.opmModelName;
	  opmModelNameHasBeenSet = true;
	  this.enabled = otherValue.enabled;
	  enabledHasBeenSet = true;
	  this.creationTime = otherValue.creationTime;
	  creationTimeHasBeenSet = true;
	  this.description = otherValue.description;
	  descriptionHasBeenSet = true;
	  this.workgroupID = otherValue.workgroupID;
	  workgroupIDHasBeenSet = true;
	  this.totalCollaborativeTime = otherValue.totalCollaborativeTime;
	  totalCollaborativeTimeHasBeenSet = true;
	// TODO Clone is better no ?
	  this.OpmModelsPermissions = otherValue.OpmModelsPermissions;

	  pk = this.getOpmModelID();
   }

   public java.lang.String getPrimaryKey()
   {
	  return pk;
   }

   public void setPrimaryKey( java.lang.String pk )
   {
      // it's also nice to update PK object - just in case
      // somebody would ask for it later...
      this.pk = pk;
	  setOpmModelID( pk );
   }

   public java.lang.String getOpmModelID()
   {
	  return this.opmModelID;
   }

   public void setOpmModelID( java.lang.String opmModelID )
   {
	  this.opmModelID = opmModelID;
	  opmModelIDHasBeenSet = true;

		  pk = opmModelID;
   }

   public boolean opmModelIDHasBeenSet(){
	  return opmModelIDHasBeenSet;
   }
   public java.lang.String getOpmModelName()
   {
	  return this.opmModelName;
   }

   public void setOpmModelName( java.lang.String opmModelName )
   {
	  this.opmModelName = opmModelName;
	  opmModelNameHasBeenSet = true;

   }

   public boolean opmModelNameHasBeenSet(){
	  return opmModelNameHasBeenSet;
   }
   public java.lang.Boolean getEnabled()
   {
	  return this.enabled;
   }

   public void setEnabled( java.lang.Boolean enabled )
   {
	  this.enabled = enabled;
	  enabledHasBeenSet = true;

   }

   public boolean enabledHasBeenSet(){
	  return enabledHasBeenSet;
   }
   public java.util.Date getCreationTime()
   {
	  return this.creationTime;
   }

   public void setCreationTime( java.util.Date creationTime )
   {
	  this.creationTime = creationTime;
	  creationTimeHasBeenSet = true;

   }

   public boolean creationTimeHasBeenSet(){
	  return creationTimeHasBeenSet;
   }
   public java.lang.String getDescription()
   {
	  return this.description;
   }

   public void setDescription( java.lang.String description )
   {
	  this.description = description;
	  descriptionHasBeenSet = true;

   }

   public boolean descriptionHasBeenSet(){
	  return descriptionHasBeenSet;
   }
   public java.lang.String getWorkgroupID()
   {
	  return this.workgroupID;
   }

   public void setWorkgroupID( java.lang.String workgroupID )
   {
	  this.workgroupID = workgroupID;
	  workgroupIDHasBeenSet = true;

   }

   public boolean workgroupIDHasBeenSet(){
	  return workgroupIDHasBeenSet;
   }
   public java.lang.Integer getTotalCollaborativeTime()
   {
	  return this.totalCollaborativeTime;
   }

   public void setTotalCollaborativeTime( java.lang.Integer totalCollaborativeTime )
   {
	  this.totalCollaborativeTime = totalCollaborativeTime;
	  totalCollaborativeTimeHasBeenSet = true;

   }

   public boolean totalCollaborativeTimeHasBeenSet(){
	  return totalCollaborativeTimeHasBeenSet;
   }

   protected java.util.Collection addedOpmModelsPermissions = new java.util.ArrayList();
   protected java.util.Collection onceAddedOpmModelsPermissions = new java.util.ArrayList();
   protected java.util.Collection removedOpmModelsPermissions = new java.util.ArrayList();
   protected java.util.Collection updatedOpmModelsPermissions = new java.util.ArrayList();

   public java.util.Collection getAddedOpmModelsPermissions() { return addedOpmModelsPermissions; }
   public java.util.Collection getOnceAddedOpmModelsPermissions() { return onceAddedOpmModelsPermissions; }
   public java.util.Collection getRemovedOpmModelsPermissions() { return removedOpmModelsPermissions; }
   public java.util.Collection getUpdatedOpmModelsPermissions() { return updatedOpmModelsPermissions; }

   public void setAddedOpmModelsPermissions(java.util.Collection addedOpmModelsPermissions)
   {
      this.addedOpmModelsPermissions.clear();
      this.addedOpmModelsPermissions.addAll(addedOpmModelsPermissions);
   }

   public void setOnceAddedOpmModelsPermissions(java.util.Collection onceAddedOpmModelsPermissions)
   {
      this.onceAddedOpmModelsPermissions.clear();
      this.onceAddedOpmModelsPermissions.addAll(onceAddedOpmModelsPermissions);
   }

   public void setRemovedOpmModelsPermissions(java.util.Collection removedOpmModelsPermissions)
   {
      this.removedOpmModelsPermissions.clear();
      this.removedOpmModelsPermissions.addAll(removedOpmModelsPermissions);
   }

   public void setUpdatedOpmModelsPermissions(java.util.Collection updatedOpmModelsPermissions)
   {
      this.updatedOpmModelsPermissions.clear();
      this.updatedOpmModelsPermissions.addAll(updatedOpmModelsPermissions);
   }

   public org.objectprocess.cmp.Enhanced2OpmModelPermissionsValue[] getOpmModelsPermissions()
   {
	  return (org.objectprocess.cmp.Enhanced2OpmModelPermissionsValue[])this.OpmModelsPermissions.toArray(new org.objectprocess.cmp.Enhanced2OpmModelPermissionsValue[OpmModelsPermissions.size()]);
   }

   public void setOpmModelsPermissions(org.objectprocess.cmp.Enhanced2OpmModelPermissionsValue[] OpmModelsPermissions)
   {
      this.OpmModelsPermissions.clear();
      for (int i=0; i < OpmModelsPermissions.length; i++)
      	this.OpmModelsPermissions.add(OpmModelsPermissions[i]);
   }

   public void clearOpmModelsPermissions()
   {
	  this.OpmModelsPermissions.clear();
   }

   public void addOpmModelsPermission(org.objectprocess.cmp.Enhanced2OpmModelPermissionsValue added)
   {
	  this.OpmModelsPermissions.add(added);

      if (this.removedOpmModelsPermissions.contains(added))
      {
        this.removedOpmModelsPermissions.remove(added);
        if (this.onceAddedOpmModelsPermissions.contains(added))
        {
          if (! this.addedOpmModelsPermissions.contains(added))
            this.addedOpmModelsPermissions.add(added);
        }
        else if (! this.updatedOpmModelsPermissions.contains(added))
        {
            this.updatedOpmModelsPermissions.add(added);
        }
      }
      else
      {
        if (! this.onceAddedOpmModelsPermissions.contains(added))
          this.onceAddedOpmModelsPermissions.add(added);
        if (! this.addedOpmModelsPermissions.contains(added))
          this.addedOpmModelsPermissions.add(added);
      }
   }

   public void removeOpmModelsPermission(org.objectprocess.cmp.Enhanced2OpmModelPermissionsValue removed)
   {
	  this.OpmModelsPermissions.remove(removed);

      if (this.addedOpmModelsPermissions.contains(removed))
        this.addedOpmModelsPermissions.remove(removed);
      else if (! this.removedOpmModelsPermissions.contains(removed))
        this.removedOpmModelsPermissions.add(removed);

	  if (this.updatedOpmModelsPermissions.contains(removed))
		 this.updatedOpmModelsPermissions.remove(removed);
   }

   public void updateOpmModelsPermission(org.objectprocess.cmp.Enhanced2OpmModelPermissionsValue updated)
   {
	  if ( !this.updatedOpmModelsPermissions.contains(updated) && !this.addedOpmModelsPermissions.contains(updated))
		 this.updatedOpmModelsPermissions.add(updated);
      if (this.removedOpmModelsPermissions.contains(updated))
         this.removedOpmModelsPermissions.remove(updated);
   }

   public void cleanOpmModelsPermission(){
	  this.addedOpmModelsPermissions = new java.util.ArrayList();
      this.onceAddedOpmModelsPermissions = new java.util.ArrayList();
	  this.removedOpmModelsPermissions = new java.util.ArrayList();
	  this.updatedOpmModelsPermissions = new java.util.ArrayList();
   }

   public void copyOpmModelsPermissionsFrom(org.objectprocess.cmp.EnhancedOpmModelValue from)
   {
	  // TODO Clone the List ????
	  this.OpmModelsPermissions = from.OpmModelsPermissions;
   }

   public String toString()
   {
	  StringBuffer str = new StringBuffer("{");

	  str.append("opmModelID=" + getOpmModelID() + " " + "opmModelName=" + getOpmModelName() + " " + "enabled=" + getEnabled() + " " + "creationTime=" + getCreationTime() + " " + "description=" + getDescription() + " " + "workgroupID=" + getWorkgroupID() + " " + "totalCollaborativeTime=" + getTotalCollaborativeTime());
	  str.append('}');

	  return(str.toString());
   }

   /**
    * A Value Object has an identity if the attributes making its Primary Key have all been set. An object without identity is never equal to any other object.
    *
    * @return true if this instance has an identity.
    */
   protected boolean hasIdentity()
   {
	  return opmModelIDHasBeenSet;
   }

   public boolean equals(Object other)
   {
      if (this == other)
         return true;
	  if ( ! hasIdentity() ) return false;
	  if (other instanceof EnhancedOpmModelValue)
	  {
		 EnhancedOpmModelValue that = (EnhancedOpmModelValue) other;
		 if ( ! that.hasIdentity() ) return false;
		 boolean lEquals = true;
		 if( this.opmModelID == null )
		 {
			lEquals = lEquals && ( that.opmModelID == null );
		 }
		 else
		 {
			lEquals = lEquals && this.opmModelID.equals( that.opmModelID );
		 }

		 lEquals = lEquals && isIdentical(that);

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public boolean isIdentical(Object other)
   {
	  if (other instanceof EnhancedOpmModelValue)
	  {
		 EnhancedOpmModelValue that = (EnhancedOpmModelValue) other;
		 boolean lEquals = true;
		 if( this.opmModelName == null )
		 {
			lEquals = lEquals && ( that.opmModelName == null );
		 }
		 else
		 {
			lEquals = lEquals && this.opmModelName.equals( that.opmModelName );
		 }
		 if( this.enabled == null )
		 {
			lEquals = lEquals && ( that.enabled == null );
		 }
		 else
		 {
			lEquals = lEquals && this.enabled.equals( that.enabled );
		 }
		 if( this.creationTime == null )
		 {
			lEquals = lEquals && ( that.creationTime == null );
		 }
		 else
		 {
			lEquals = lEquals && this.creationTime.equals( that.creationTime );
		 }
		 if( this.description == null )
		 {
			lEquals = lEquals && ( that.description == null );
		 }
		 else
		 {
			lEquals = lEquals && this.description.equals( that.description );
		 }
		 if( this.workgroupID == null )
		 {
			lEquals = lEquals && ( that.workgroupID == null );
		 }
		 else
		 {
			lEquals = lEquals && this.workgroupID.equals( that.workgroupID );
		 }
		 if( this.totalCollaborativeTime == null )
		 {
			lEquals = lEquals && ( that.totalCollaborativeTime == null );
		 }
		 else
		 {
			lEquals = lEquals && this.totalCollaborativeTime.equals( that.totalCollaborativeTime );
		 }
		 if( this.getOpmModelsPermissions() == null )
		 {
			lEquals = lEquals && ( that.getOpmModelsPermissions() == null );
		 }
		 else
		 {
			lEquals = lEquals && java.util.Arrays.equals(this.getOpmModelsPermissions() , that.getOpmModelsPermissions()) ;
		 }

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public int hashCode(){
	  int result = 17;
      result = 37*result + ((this.opmModelID != null) ? this.opmModelID.hashCode() : 0);

      result = 37*result + ((this.opmModelName != null) ? this.opmModelName.hashCode() : 0);

      result = 37*result + ((this.enabled != null) ? this.enabled.hashCode() : 0);

      result = 37*result + ((this.creationTime != null) ? this.creationTime.hashCode() : 0);

      result = 37*result + ((this.description != null) ? this.description.hashCode() : 0);

      result = 37*result + ((this.workgroupID != null) ? this.workgroupID.hashCode() : 0);

      result = 37*result + ((this.totalCollaborativeTime != null) ? this.totalCollaborativeTime.hashCode() : 0);

	  result = 37*result + ((this.getOpmModelsPermissions() != null) ? this.getOpmModelsPermissions().hashCode() : 0);
	  return result;
   }

}
