/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Value object for CollaborativeSession.
 *
 * @lomboz generated
 */
public class EnhancedCollaborativeSessionValue
   extends java.lang.Object
   implements java.io.Serializable 
{
   private java.lang.String collaborativeSessionID;
   private boolean collaborativeSessionIDHasBeenSet = false;
   private java.lang.String collaborativeSessionName;
   private boolean collaborativeSessionNameHasBeenSet = false;
   private java.lang.Boolean enabled;
   private boolean enabledHasBeenSet = false;
   private java.lang.Boolean terminated;
   private boolean terminatedHasBeenSet = false;
   private java.util.Date creationTime;
   private boolean creationTimeHasBeenSet = false;
   private java.lang.String description;
   private boolean descriptionHasBeenSet = false;
   private java.util.Date lastUpdate;
   private boolean lastUpdateHasBeenSet = false;
   private java.lang.String opmModelID;
   private boolean opmModelIDHasBeenSet = false;
   private java.lang.String revisionID;
   private boolean revisionIDHasBeenSet = false;
   private java.lang.Integer tokenTimeout;
   private boolean tokenTimeoutHasBeenSet = false;
   private java.lang.Integer userTimeout;
   private boolean userTimeoutHasBeenSet = false;
   private java.lang.String tokenHolderID;
   private boolean tokenHolderIDHasBeenSet = false;
   private java.util.Collection CollaborativeSessionsPermissions = new java.util.ArrayList();

   private java.lang.String pk;

   public EnhancedCollaborativeSessionValue()
   {
   }

   public EnhancedCollaborativeSessionValue( java.lang.String collaborativeSessionID,java.lang.String collaborativeSessionName,java.lang.Boolean enabled,java.lang.Boolean terminated,java.util.Date creationTime,java.lang.String description,java.util.Date lastUpdate,java.lang.String opmModelID,java.lang.String revisionID,java.lang.Integer tokenTimeout,java.lang.Integer userTimeout,java.lang.String tokenHolderID )
   {
	  this.collaborativeSessionID = collaborativeSessionID;
	  collaborativeSessionIDHasBeenSet = true;
	  this.collaborativeSessionName = collaborativeSessionName;
	  collaborativeSessionNameHasBeenSet = true;
	  this.enabled = enabled;
	  enabledHasBeenSet = true;
	  this.terminated = terminated;
	  terminatedHasBeenSet = true;
	  this.creationTime = creationTime;
	  creationTimeHasBeenSet = true;
	  this.description = description;
	  descriptionHasBeenSet = true;
	  this.lastUpdate = lastUpdate;
	  lastUpdateHasBeenSet = true;
	  this.opmModelID = opmModelID;
	  opmModelIDHasBeenSet = true;
	  this.revisionID = revisionID;
	  revisionIDHasBeenSet = true;
	  this.tokenTimeout = tokenTimeout;
	  tokenTimeoutHasBeenSet = true;
	  this.userTimeout = userTimeout;
	  userTimeoutHasBeenSet = true;
	  this.tokenHolderID = tokenHolderID;
	  tokenHolderIDHasBeenSet = true;
	  pk = this.getCollaborativeSessionID();
   }

   //TODO Cloneable is better than this !
   public EnhancedCollaborativeSessionValue( EnhancedCollaborativeSessionValue otherValue )
   {
	  this.collaborativeSessionID = otherValue.collaborativeSessionID;
	  collaborativeSessionIDHasBeenSet = true;
	  this.collaborativeSessionName = otherValue.collaborativeSessionName;
	  collaborativeSessionNameHasBeenSet = true;
	  this.enabled = otherValue.enabled;
	  enabledHasBeenSet = true;
	  this.terminated = otherValue.terminated;
	  terminatedHasBeenSet = true;
	  this.creationTime = otherValue.creationTime;
	  creationTimeHasBeenSet = true;
	  this.description = otherValue.description;
	  descriptionHasBeenSet = true;
	  this.lastUpdate = otherValue.lastUpdate;
	  lastUpdateHasBeenSet = true;
	  this.opmModelID = otherValue.opmModelID;
	  opmModelIDHasBeenSet = true;
	  this.revisionID = otherValue.revisionID;
	  revisionIDHasBeenSet = true;
	  this.tokenTimeout = otherValue.tokenTimeout;
	  tokenTimeoutHasBeenSet = true;
	  this.userTimeout = otherValue.userTimeout;
	  userTimeoutHasBeenSet = true;
	  this.tokenHolderID = otherValue.tokenHolderID;
	  tokenHolderIDHasBeenSet = true;
	// TODO Clone is better no ?
	  this.CollaborativeSessionsPermissions = otherValue.CollaborativeSessionsPermissions;

	  pk = this.getCollaborativeSessionID();
   }

   public java.lang.String getPrimaryKey()
   {
	  return pk;
   }

   public void setPrimaryKey( java.lang.String pk )
   {
      // it's also nice to update PK object - just in case
      // somebody would ask for it later...
      this.pk = pk;
	  setCollaborativeSessionID( pk );
   }

   public java.lang.String getCollaborativeSessionID()
   {
	  return this.collaborativeSessionID;
   }

   public void setCollaborativeSessionID( java.lang.String collaborativeSessionID )
   {
	  this.collaborativeSessionID = collaborativeSessionID;
	  collaborativeSessionIDHasBeenSet = true;

		  pk = collaborativeSessionID;
   }

   public boolean collaborativeSessionIDHasBeenSet(){
	  return collaborativeSessionIDHasBeenSet;
   }
   public java.lang.String getCollaborativeSessionName()
   {
	  return this.collaborativeSessionName;
   }

   public void setCollaborativeSessionName( java.lang.String collaborativeSessionName )
   {
	  this.collaborativeSessionName = collaborativeSessionName;
	  collaborativeSessionNameHasBeenSet = true;

   }

   public boolean collaborativeSessionNameHasBeenSet(){
	  return collaborativeSessionNameHasBeenSet;
   }
   public java.lang.Boolean getEnabled()
   {
	  return this.enabled;
   }

   public void setEnabled( java.lang.Boolean enabled )
   {
	  this.enabled = enabled;
	  enabledHasBeenSet = true;

   }

   public boolean enabledHasBeenSet(){
	  return enabledHasBeenSet;
   }
   public java.lang.Boolean getTerminated()
   {
	  return this.terminated;
   }

   public void setTerminated( java.lang.Boolean terminated )
   {
	  this.terminated = terminated;
	  terminatedHasBeenSet = true;

   }

   public boolean terminatedHasBeenSet(){
	  return terminatedHasBeenSet;
   }
   public java.util.Date getCreationTime()
   {
	  return this.creationTime;
   }

   public void setCreationTime( java.util.Date creationTime )
   {
	  this.creationTime = creationTime;
	  creationTimeHasBeenSet = true;

   }

   public boolean creationTimeHasBeenSet(){
	  return creationTimeHasBeenSet;
   }
   public java.lang.String getDescription()
   {
	  return this.description;
   }

   public void setDescription( java.lang.String description )
   {
	  this.description = description;
	  descriptionHasBeenSet = true;

   }

   public boolean descriptionHasBeenSet(){
	  return descriptionHasBeenSet;
   }
   public java.util.Date getLastUpdate()
   {
	  return this.lastUpdate;
   }

   public void setLastUpdate( java.util.Date lastUpdate )
   {
	  this.lastUpdate = lastUpdate;
	  lastUpdateHasBeenSet = true;

   }

   public boolean lastUpdateHasBeenSet(){
	  return lastUpdateHasBeenSet;
   }
   public java.lang.String getOpmModelID()
   {
	  return this.opmModelID;
   }

   public void setOpmModelID( java.lang.String opmModelID )
   {
	  this.opmModelID = opmModelID;
	  opmModelIDHasBeenSet = true;

   }

   public boolean opmModelIDHasBeenSet(){
	  return opmModelIDHasBeenSet;
   }
   public java.lang.String getRevisionID()
   {
	  return this.revisionID;
   }

   public void setRevisionID( java.lang.String revisionID )
   {
	  this.revisionID = revisionID;
	  revisionIDHasBeenSet = true;

   }

   public boolean revisionIDHasBeenSet(){
	  return revisionIDHasBeenSet;
   }
   public java.lang.Integer getTokenTimeout()
   {
	  return this.tokenTimeout;
   }

   public void setTokenTimeout( java.lang.Integer tokenTimeout )
   {
	  this.tokenTimeout = tokenTimeout;
	  tokenTimeoutHasBeenSet = true;

   }

   public boolean tokenTimeoutHasBeenSet(){
	  return tokenTimeoutHasBeenSet;
   }
   public java.lang.Integer getUserTimeout()
   {
	  return this.userTimeout;
   }

   public void setUserTimeout( java.lang.Integer userTimeout )
   {
	  this.userTimeout = userTimeout;
	  userTimeoutHasBeenSet = true;

   }

   public boolean userTimeoutHasBeenSet(){
	  return userTimeoutHasBeenSet;
   }
   public java.lang.String getTokenHolderID()
   {
	  return this.tokenHolderID;
   }

   public void setTokenHolderID( java.lang.String tokenHolderID )
   {
	  this.tokenHolderID = tokenHolderID;
	  tokenHolderIDHasBeenSet = true;

   }

   public boolean tokenHolderIDHasBeenSet(){
	  return tokenHolderIDHasBeenSet;
   }

   protected java.util.Collection addedCollaborativeSessionsPermissions = new java.util.ArrayList();
   protected java.util.Collection onceAddedCollaborativeSessionsPermissions = new java.util.ArrayList();
   protected java.util.Collection removedCollaborativeSessionsPermissions = new java.util.ArrayList();
   protected java.util.Collection updatedCollaborativeSessionsPermissions = new java.util.ArrayList();

   public java.util.Collection getAddedCollaborativeSessionsPermissions() { return addedCollaborativeSessionsPermissions; }
   public java.util.Collection getOnceAddedCollaborativeSessionsPermissions() { return onceAddedCollaborativeSessionsPermissions; }
   public java.util.Collection getRemovedCollaborativeSessionsPermissions() { return removedCollaborativeSessionsPermissions; }
   public java.util.Collection getUpdatedCollaborativeSessionsPermissions() { return updatedCollaborativeSessionsPermissions; }

   public void setAddedCollaborativeSessionsPermissions(java.util.Collection addedCollaborativeSessionsPermissions)
   {
      this.addedCollaborativeSessionsPermissions.clear();
      this.addedCollaborativeSessionsPermissions.addAll(addedCollaborativeSessionsPermissions);
   }

   public void setOnceAddedCollaborativeSessionsPermissions(java.util.Collection onceAddedCollaborativeSessionsPermissions)
   {
      this.onceAddedCollaborativeSessionsPermissions.clear();
      this.onceAddedCollaborativeSessionsPermissions.addAll(onceAddedCollaborativeSessionsPermissions);
   }

   public void setRemovedCollaborativeSessionsPermissions(java.util.Collection removedCollaborativeSessionsPermissions)
   {
      this.removedCollaborativeSessionsPermissions.clear();
      this.removedCollaborativeSessionsPermissions.addAll(removedCollaborativeSessionsPermissions);
   }

   public void setUpdatedCollaborativeSessionsPermissions(java.util.Collection updatedCollaborativeSessionsPermissions)
   {
      this.updatedCollaborativeSessionsPermissions.clear();
      this.updatedCollaborativeSessionsPermissions.addAll(updatedCollaborativeSessionsPermissions);
   }

   public org.objectprocess.cmp.Enhanced2CollaborativeSessionPermissionsValue[] getCollaborativeSessionsPermissions()
   {
	  return (org.objectprocess.cmp.Enhanced2CollaborativeSessionPermissionsValue[])this.CollaborativeSessionsPermissions.toArray(new org.objectprocess.cmp.Enhanced2CollaborativeSessionPermissionsValue[CollaborativeSessionsPermissions.size()]);
   }

   public void setCollaborativeSessionsPermissions(org.objectprocess.cmp.Enhanced2CollaborativeSessionPermissionsValue[] CollaborativeSessionsPermissions)
   {
      this.CollaborativeSessionsPermissions.clear();
      for (int i=0; i < CollaborativeSessionsPermissions.length; i++)
      	this.CollaborativeSessionsPermissions.add(CollaborativeSessionsPermissions[i]);
   }

   public void clearCollaborativeSessionsPermissions()
   {
	  this.CollaborativeSessionsPermissions.clear();
   }

   public void addCollaborativeSessionsPermission(org.objectprocess.cmp.Enhanced2CollaborativeSessionPermissionsValue added)
   {
	  this.CollaborativeSessionsPermissions.add(added);

      if (this.removedCollaborativeSessionsPermissions.contains(added))
      {
        this.removedCollaborativeSessionsPermissions.remove(added);
        if (this.onceAddedCollaborativeSessionsPermissions.contains(added))
        {
          if (! this.addedCollaborativeSessionsPermissions.contains(added))
            this.addedCollaborativeSessionsPermissions.add(added);
        }
        else if (! this.updatedCollaborativeSessionsPermissions.contains(added))
        {
            this.updatedCollaborativeSessionsPermissions.add(added);
        }
      }
      else
      {
        if (! this.onceAddedCollaborativeSessionsPermissions.contains(added))
          this.onceAddedCollaborativeSessionsPermissions.add(added);
        if (! this.addedCollaborativeSessionsPermissions.contains(added))
          this.addedCollaborativeSessionsPermissions.add(added);
      }
   }

   public void removeCollaborativeSessionsPermission(org.objectprocess.cmp.Enhanced2CollaborativeSessionPermissionsValue removed)
   {
	  this.CollaborativeSessionsPermissions.remove(removed);

      if (this.addedCollaborativeSessionsPermissions.contains(removed))
        this.addedCollaborativeSessionsPermissions.remove(removed);
      else if (! this.removedCollaborativeSessionsPermissions.contains(removed))
        this.removedCollaborativeSessionsPermissions.add(removed);

	  if (this.updatedCollaborativeSessionsPermissions.contains(removed))
		 this.updatedCollaborativeSessionsPermissions.remove(removed);
   }

   public void updateCollaborativeSessionsPermission(org.objectprocess.cmp.Enhanced2CollaborativeSessionPermissionsValue updated)
   {
	  if ( !this.updatedCollaborativeSessionsPermissions.contains(updated) && !this.addedCollaborativeSessionsPermissions.contains(updated))
		 this.updatedCollaborativeSessionsPermissions.add(updated);
      if (this.removedCollaborativeSessionsPermissions.contains(updated))
         this.removedCollaborativeSessionsPermissions.remove(updated);
   }

   public void cleanCollaborativeSessionsPermission(){
	  this.addedCollaborativeSessionsPermissions = new java.util.ArrayList();
      this.onceAddedCollaborativeSessionsPermissions = new java.util.ArrayList();
	  this.removedCollaborativeSessionsPermissions = new java.util.ArrayList();
	  this.updatedCollaborativeSessionsPermissions = new java.util.ArrayList();
   }

   public void copyCollaborativeSessionsPermissionsFrom(org.objectprocess.cmp.EnhancedCollaborativeSessionValue from)
   {
	  // TODO Clone the List ????
	  this.CollaborativeSessionsPermissions = from.CollaborativeSessionsPermissions;
   }

   public String toString()
   {
	  StringBuffer str = new StringBuffer("{");

	  str.append("collaborativeSessionID=" + getCollaborativeSessionID() + " " + "collaborativeSessionName=" + getCollaborativeSessionName() + " " + "enabled=" + getEnabled() + " " + "terminated=" + getTerminated() + " " + "creationTime=" + getCreationTime() + " " + "description=" + getDescription() + " " + "lastUpdate=" + getLastUpdate() + " " + "opmModelID=" + getOpmModelID() + " " + "revisionID=" + getRevisionID() + " " + "tokenTimeout=" + getTokenTimeout() + " " + "userTimeout=" + getUserTimeout() + " " + "tokenHolderID=" + getTokenHolderID());
	  str.append('}');

	  return(str.toString());
   }

   /**
    * A Value Object has an identity if the attributes making its Primary Key have all been set. An object without identity is never equal to any other object.
    *
    * @return true if this instance has an identity.
    */
   protected boolean hasIdentity()
   {
	  return collaborativeSessionIDHasBeenSet;
   }

   public boolean equals(Object other)
   {
      if (this == other)
         return true;
	  if ( ! hasIdentity() ) return false;
	  if (other instanceof EnhancedCollaborativeSessionValue)
	  {
		 EnhancedCollaborativeSessionValue that = (EnhancedCollaborativeSessionValue) other;
		 if ( ! that.hasIdentity() ) return false;
		 boolean lEquals = true;
		 if( this.collaborativeSessionID == null )
		 {
			lEquals = lEquals && ( that.collaborativeSessionID == null );
		 }
		 else
		 {
			lEquals = lEquals && this.collaborativeSessionID.equals( that.collaborativeSessionID );
		 }

		 lEquals = lEquals && isIdentical(that);

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public boolean isIdentical(Object other)
   {
	  if (other instanceof EnhancedCollaborativeSessionValue)
	  {
		 EnhancedCollaborativeSessionValue that = (EnhancedCollaborativeSessionValue) other;
		 boolean lEquals = true;
		 if( this.collaborativeSessionName == null )
		 {
			lEquals = lEquals && ( that.collaborativeSessionName == null );
		 }
		 else
		 {
			lEquals = lEquals && this.collaborativeSessionName.equals( that.collaborativeSessionName );
		 }
		 if( this.enabled == null )
		 {
			lEquals = lEquals && ( that.enabled == null );
		 }
		 else
		 {
			lEquals = lEquals && this.enabled.equals( that.enabled );
		 }
		 if( this.terminated == null )
		 {
			lEquals = lEquals && ( that.terminated == null );
		 }
		 else
		 {
			lEquals = lEquals && this.terminated.equals( that.terminated );
		 }
		 if( this.creationTime == null )
		 {
			lEquals = lEquals && ( that.creationTime == null );
		 }
		 else
		 {
			lEquals = lEquals && this.creationTime.equals( that.creationTime );
		 }
		 if( this.description == null )
		 {
			lEquals = lEquals && ( that.description == null );
		 }
		 else
		 {
			lEquals = lEquals && this.description.equals( that.description );
		 }
		 if( this.lastUpdate == null )
		 {
			lEquals = lEquals && ( that.lastUpdate == null );
		 }
		 else
		 {
			lEquals = lEquals && this.lastUpdate.equals( that.lastUpdate );
		 }
		 if( this.opmModelID == null )
		 {
			lEquals = lEquals && ( that.opmModelID == null );
		 }
		 else
		 {
			lEquals = lEquals && this.opmModelID.equals( that.opmModelID );
		 }
		 if( this.revisionID == null )
		 {
			lEquals = lEquals && ( that.revisionID == null );
		 }
		 else
		 {
			lEquals = lEquals && this.revisionID.equals( that.revisionID );
		 }
		 if( this.tokenTimeout == null )
		 {
			lEquals = lEquals && ( that.tokenTimeout == null );
		 }
		 else
		 {
			lEquals = lEquals && this.tokenTimeout.equals( that.tokenTimeout );
		 }
		 if( this.userTimeout == null )
		 {
			lEquals = lEquals && ( that.userTimeout == null );
		 }
		 else
		 {
			lEquals = lEquals && this.userTimeout.equals( that.userTimeout );
		 }
		 if( this.tokenHolderID == null )
		 {
			lEquals = lEquals && ( that.tokenHolderID == null );
		 }
		 else
		 {
			lEquals = lEquals && this.tokenHolderID.equals( that.tokenHolderID );
		 }
		 if( this.getCollaborativeSessionsPermissions() == null )
		 {
			lEquals = lEquals && ( that.getCollaborativeSessionsPermissions() == null );
		 }
		 else
		 {
			lEquals = lEquals && java.util.Arrays.equals(this.getCollaborativeSessionsPermissions() , that.getCollaborativeSessionsPermissions()) ;
		 }

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public int hashCode(){
	  int result = 17;
      result = 37*result + ((this.collaborativeSessionID != null) ? this.collaborativeSessionID.hashCode() : 0);

      result = 37*result + ((this.collaborativeSessionName != null) ? this.collaborativeSessionName.hashCode() : 0);

      result = 37*result + ((this.enabled != null) ? this.enabled.hashCode() : 0);

      result = 37*result + ((this.terminated != null) ? this.terminated.hashCode() : 0);

      result = 37*result + ((this.creationTime != null) ? this.creationTime.hashCode() : 0);

      result = 37*result + ((this.description != null) ? this.description.hashCode() : 0);

      result = 37*result + ((this.lastUpdate != null) ? this.lastUpdate.hashCode() : 0);

      result = 37*result + ((this.opmModelID != null) ? this.opmModelID.hashCode() : 0);

      result = 37*result + ((this.revisionID != null) ? this.revisionID.hashCode() : 0);

      result = 37*result + ((this.tokenTimeout != null) ? this.tokenTimeout.hashCode() : 0);

      result = 37*result + ((this.userTimeout != null) ? this.userTimeout.hashCode() : 0);

      result = 37*result + ((this.tokenHolderID != null) ? this.tokenHolderID.hashCode() : 0);

	  result = 37*result + ((this.getCollaborativeSessionsPermissions() != null) ? this.getCollaborativeSessionsPermissions().hashCode() : 0);
	  return result;
   }

}
