/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Value object for Workgroup.
 *
 * @lomboz generated
 */
public class EnhancedWorkgroupValue
   extends java.lang.Object
   implements java.io.Serializable 
{
   private java.lang.String workgroupID;
   private boolean workgroupIDHasBeenSet = false;
   private java.lang.String workgroupName;
   private boolean workgroupNameHasBeenSet = false;
   private java.lang.Boolean enabled;
   private boolean enabledHasBeenSet = false;
   private java.util.Date creationTime;
   private boolean creationTimeHasBeenSet = false;
   private java.lang.String description;
   private boolean descriptionHasBeenSet = false;
   private java.util.Collection WorkgroupsPermissions = new java.util.ArrayList();

   private java.lang.String pk;

   public EnhancedWorkgroupValue()
   {
   }

   public EnhancedWorkgroupValue( java.lang.String workgroupID,java.lang.String workgroupName,java.lang.Boolean enabled,java.util.Date creationTime,java.lang.String description )
   {
	  this.workgroupID = workgroupID;
	  workgroupIDHasBeenSet = true;
	  this.workgroupName = workgroupName;
	  workgroupNameHasBeenSet = true;
	  this.enabled = enabled;
	  enabledHasBeenSet = true;
	  this.creationTime = creationTime;
	  creationTimeHasBeenSet = true;
	  this.description = description;
	  descriptionHasBeenSet = true;
	  pk = this.getWorkgroupID();
   }

   //TODO Cloneable is better than this !
   public EnhancedWorkgroupValue( EnhancedWorkgroupValue otherValue )
   {
	  this.workgroupID = otherValue.workgroupID;
	  workgroupIDHasBeenSet = true;
	  this.workgroupName = otherValue.workgroupName;
	  workgroupNameHasBeenSet = true;
	  this.enabled = otherValue.enabled;
	  enabledHasBeenSet = true;
	  this.creationTime = otherValue.creationTime;
	  creationTimeHasBeenSet = true;
	  this.description = otherValue.description;
	  descriptionHasBeenSet = true;
	// TODO Clone is better no ?
	  this.WorkgroupsPermissions = otherValue.WorkgroupsPermissions;

	  pk = this.getWorkgroupID();
   }

   public java.lang.String getPrimaryKey()
   {
	  return pk;
   }

   public void setPrimaryKey( java.lang.String pk )
   {
      // it's also nice to update PK object - just in case
      // somebody would ask for it later...
      this.pk = pk;
	  setWorkgroupID( pk );
   }

   public java.lang.String getWorkgroupID()
   {
	  return this.workgroupID;
   }

   public void setWorkgroupID( java.lang.String workgroupID )
   {
	  this.workgroupID = workgroupID;
	  workgroupIDHasBeenSet = true;

		  pk = workgroupID;
   }

   public boolean workgroupIDHasBeenSet(){
	  return workgroupIDHasBeenSet;
   }
   public java.lang.String getWorkgroupName()
   {
	  return this.workgroupName;
   }

   public void setWorkgroupName( java.lang.String workgroupName )
   {
	  this.workgroupName = workgroupName;
	  workgroupNameHasBeenSet = true;

   }

   public boolean workgroupNameHasBeenSet(){
	  return workgroupNameHasBeenSet;
   }
   public java.lang.Boolean getEnabled()
   {
	  return this.enabled;
   }

   public void setEnabled( java.lang.Boolean enabled )
   {
	  this.enabled = enabled;
	  enabledHasBeenSet = true;

   }

   public boolean enabledHasBeenSet(){
	  return enabledHasBeenSet;
   }
   public java.util.Date getCreationTime()
   {
	  return this.creationTime;
   }

   public void setCreationTime( java.util.Date creationTime )
   {
	  this.creationTime = creationTime;
	  creationTimeHasBeenSet = true;

   }

   public boolean creationTimeHasBeenSet(){
	  return creationTimeHasBeenSet;
   }
   public java.lang.String getDescription()
   {
	  return this.description;
   }

   public void setDescription( java.lang.String description )
   {
	  this.description = description;
	  descriptionHasBeenSet = true;

   }

   public boolean descriptionHasBeenSet(){
	  return descriptionHasBeenSet;
   }

   protected java.util.Collection addedWorkgroupsPermissions = new java.util.ArrayList();
   protected java.util.Collection onceAddedWorkgroupsPermissions = new java.util.ArrayList();
   protected java.util.Collection removedWorkgroupsPermissions = new java.util.ArrayList();
   protected java.util.Collection updatedWorkgroupsPermissions = new java.util.ArrayList();

   public java.util.Collection getAddedWorkgroupsPermissions() { return addedWorkgroupsPermissions; }
   public java.util.Collection getOnceAddedWorkgroupsPermissions() { return onceAddedWorkgroupsPermissions; }
   public java.util.Collection getRemovedWorkgroupsPermissions() { return removedWorkgroupsPermissions; }
   public java.util.Collection getUpdatedWorkgroupsPermissions() { return updatedWorkgroupsPermissions; }

   public void setAddedWorkgroupsPermissions(java.util.Collection addedWorkgroupsPermissions)
   {
      this.addedWorkgroupsPermissions.clear();
      this.addedWorkgroupsPermissions.addAll(addedWorkgroupsPermissions);
   }

   public void setOnceAddedWorkgroupsPermissions(java.util.Collection onceAddedWorkgroupsPermissions)
   {
      this.onceAddedWorkgroupsPermissions.clear();
      this.onceAddedWorkgroupsPermissions.addAll(onceAddedWorkgroupsPermissions);
   }

   public void setRemovedWorkgroupsPermissions(java.util.Collection removedWorkgroupsPermissions)
   {
      this.removedWorkgroupsPermissions.clear();
      this.removedWorkgroupsPermissions.addAll(removedWorkgroupsPermissions);
   }

   public void setUpdatedWorkgroupsPermissions(java.util.Collection updatedWorkgroupsPermissions)
   {
      this.updatedWorkgroupsPermissions.clear();
      this.updatedWorkgroupsPermissions.addAll(updatedWorkgroupsPermissions);
   }

   public org.objectprocess.cmp.Enhanced2WorkgroupPermissionsValue[] getWorkgroupsPermissions()
   {
	  return (org.objectprocess.cmp.Enhanced2WorkgroupPermissionsValue[])this.WorkgroupsPermissions.toArray(new org.objectprocess.cmp.Enhanced2WorkgroupPermissionsValue[WorkgroupsPermissions.size()]);
   }

   public void setWorkgroupsPermissions(org.objectprocess.cmp.Enhanced2WorkgroupPermissionsValue[] WorkgroupsPermissions)
   {
      this.WorkgroupsPermissions.clear();
      for (int i=0; i < WorkgroupsPermissions.length; i++)
      	this.WorkgroupsPermissions.add(WorkgroupsPermissions[i]);
   }

   public void clearWorkgroupsPermissions()
   {
	  this.WorkgroupsPermissions.clear();
   }

   public void addWorkgroupsPermission(org.objectprocess.cmp.Enhanced2WorkgroupPermissionsValue added)
   {
	  this.WorkgroupsPermissions.add(added);

      if (this.removedWorkgroupsPermissions.contains(added))
      {
        this.removedWorkgroupsPermissions.remove(added);
        if (this.onceAddedWorkgroupsPermissions.contains(added))
        {
          if (! this.addedWorkgroupsPermissions.contains(added))
            this.addedWorkgroupsPermissions.add(added);
        }
        else if (! this.updatedWorkgroupsPermissions.contains(added))
        {
            this.updatedWorkgroupsPermissions.add(added);
        }
      }
      else
      {
        if (! this.onceAddedWorkgroupsPermissions.contains(added))
          this.onceAddedWorkgroupsPermissions.add(added);
        if (! this.addedWorkgroupsPermissions.contains(added))
          this.addedWorkgroupsPermissions.add(added);
      }
   }

   public void removeWorkgroupsPermission(org.objectprocess.cmp.Enhanced2WorkgroupPermissionsValue removed)
   {
	  this.WorkgroupsPermissions.remove(removed);

      if (this.addedWorkgroupsPermissions.contains(removed))
        this.addedWorkgroupsPermissions.remove(removed);
      else if (! this.removedWorkgroupsPermissions.contains(removed))
        this.removedWorkgroupsPermissions.add(removed);

	  if (this.updatedWorkgroupsPermissions.contains(removed))
		 this.updatedWorkgroupsPermissions.remove(removed);
   }

   public void updateWorkgroupsPermission(org.objectprocess.cmp.Enhanced2WorkgroupPermissionsValue updated)
   {
	  if ( !this.updatedWorkgroupsPermissions.contains(updated) && !this.addedWorkgroupsPermissions.contains(updated))
		 this.updatedWorkgroupsPermissions.add(updated);
      if (this.removedWorkgroupsPermissions.contains(updated))
         this.removedWorkgroupsPermissions.remove(updated);
   }

   public void cleanWorkgroupsPermission(){
	  this.addedWorkgroupsPermissions = new java.util.ArrayList();
      this.onceAddedWorkgroupsPermissions = new java.util.ArrayList();
	  this.removedWorkgroupsPermissions = new java.util.ArrayList();
	  this.updatedWorkgroupsPermissions = new java.util.ArrayList();
   }

   public void copyWorkgroupsPermissionsFrom(org.objectprocess.cmp.EnhancedWorkgroupValue from)
   {
	  // TODO Clone the List ????
	  this.WorkgroupsPermissions = from.WorkgroupsPermissions;
   }

   public String toString()
   {
	  StringBuffer str = new StringBuffer("{");

	  str.append("workgroupID=" + getWorkgroupID() + " " + "workgroupName=" + getWorkgroupName() + " " + "enabled=" + getEnabled() + " " + "creationTime=" + getCreationTime() + " " + "description=" + getDescription());
	  str.append('}');

	  return(str.toString());
   }

   /**
    * A Value Object has an identity if the attributes making its Primary Key have all been set. An object without identity is never equal to any other object.
    *
    * @return true if this instance has an identity.
    */
   protected boolean hasIdentity()
   {
	  return workgroupIDHasBeenSet;
   }

   public boolean equals(Object other)
   {
      if (this == other)
         return true;
	  if ( ! hasIdentity() ) return false;
	  if (other instanceof EnhancedWorkgroupValue)
	  {
		 EnhancedWorkgroupValue that = (EnhancedWorkgroupValue) other;
		 if ( ! that.hasIdentity() ) return false;
		 boolean lEquals = true;
		 if( this.workgroupID == null )
		 {
			lEquals = lEquals && ( that.workgroupID == null );
		 }
		 else
		 {
			lEquals = lEquals && this.workgroupID.equals( that.workgroupID );
		 }

		 lEquals = lEquals && isIdentical(that);

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public boolean isIdentical(Object other)
   {
	  if (other instanceof EnhancedWorkgroupValue)
	  {
		 EnhancedWorkgroupValue that = (EnhancedWorkgroupValue) other;
		 boolean lEquals = true;
		 if( this.workgroupName == null )
		 {
			lEquals = lEquals && ( that.workgroupName == null );
		 }
		 else
		 {
			lEquals = lEquals && this.workgroupName.equals( that.workgroupName );
		 }
		 if( this.enabled == null )
		 {
			lEquals = lEquals && ( that.enabled == null );
		 }
		 else
		 {
			lEquals = lEquals && this.enabled.equals( that.enabled );
		 }
		 if( this.creationTime == null )
		 {
			lEquals = lEquals && ( that.creationTime == null );
		 }
		 else
		 {
			lEquals = lEquals && this.creationTime.equals( that.creationTime );
		 }
		 if( this.description == null )
		 {
			lEquals = lEquals && ( that.description == null );
		 }
		 else
		 {
			lEquals = lEquals && this.description.equals( that.description );
		 }
		 if( this.getWorkgroupsPermissions() == null )
		 {
			lEquals = lEquals && ( that.getWorkgroupsPermissions() == null );
		 }
		 else
		 {
			lEquals = lEquals && java.util.Arrays.equals(this.getWorkgroupsPermissions() , that.getWorkgroupsPermissions()) ;
		 }

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public int hashCode(){
	  int result = 17;
      result = 37*result + ((this.workgroupID != null) ? this.workgroupID.hashCode() : 0);

      result = 37*result + ((this.workgroupName != null) ? this.workgroupName.hashCode() : 0);

      result = 37*result + ((this.enabled != null) ? this.enabled.hashCode() : 0);

      result = 37*result + ((this.creationTime != null) ? this.creationTime.hashCode() : 0);

      result = 37*result + ((this.description != null) ? this.description.hashCode() : 0);

	  result = 37*result + ((this.getWorkgroupsPermissions() != null) ? this.getWorkgroupsPermissions().hashCode() : 0);
	  return result;
   }

}
