/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Local interface for OpmModel.
 * @lomboz generated
 */
public interface OpmModelLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Returns a <code>Collection</code> of <code>RevisionLocal</code> related to the OPM Model.
    * @return a <code>Collection</code> of related <code>RevisionLocal</code>.
    */
   public java.util.Collection getOpmModelRevisions(  ) ;

   public void setOpmModelRevisions( java.util.Collection opmModelRevisions ) ;

   /**
    * Returns a <code>Collection</code> of <code>OpmModelPermissionsLocal</code> related to the OPM Model.
    * @return a <code>Collection</code> of related <code>OpmModelPermissionsLocal</code>.
    */
   public java.util.Collection getOpmModelPermissions(  ) ;

   public void setOpmModelPermissions( java.util.Collection opmModelPermissions ) ;

   /**
    * Returns a <code>Collection</code> of <code>CollaborativeSessionLocal</code> related to the OPM Model.
    * @return a <code>Collection</code> of related <code>CollaborativeSessionLocal</code>.
    */
   public java.util.Collection getCollaborativeSessions(  ) ;

   public void setCollaborativeSessions( java.util.Collection CollaborativeSession ) ;

   /**
    * Returns a <code>WorkgroupLocal</code> containing the OPM Model.
    * @return a <code>WorkgroupLocal</code> containing the OPM Model.
    */
   public org.objectprocess.cmp.WorkgroupLocal getWorkgroup(  ) ;

   public void setWorkgroup( org.objectprocess.cmp.WorkgroupLocal Workgroup ) ;

   /**
    * Returns the OPM model's id
    * @return the OPM model's id
    */
   public java.lang.String getOpmModelID(  ) ;

   /**
    * Sets the OPM model's id
    * @param opmModelID the new OPM model's id value
    */
   public void setOpmModelID( java.lang.String opmModelID ) ;

   /**
    * Returns the OPM model's name.
    * @return the OPM model's name.
    */
   public java.lang.String getOpmModelName(  ) ;

   /**
    * Sets the OPM model's name
    * @param opmModelName the new OPM model's name value
    */
   public void setOpmModelName( java.lang.String opmModelName ) ;

   /**
    * Returns the OPM model's <code>enabled</code> flag value.
    * @return the OPM model's <code>enabled</code> flag value.
    */
   public java.lang.Boolean getEnabled(  ) ;

   /**
    * Sets the OPM model's <code>enabled</code> flag value.
    * @param enabled the new <code>enabled</code> flag value.
    */
   public void setEnabled( java.lang.Boolean enabled ) ;

   /**
    * Returns the time the OPM model was created.
    * @return the time the OPM model was created.
    */
   public java.util.Date getCreationTime(  ) ;

   /**
    * Sets the time for OPM model creation. Initialized once, on <code>ejbCreate</code>.
    * @param CreationTime the new timestamp value
    */
   public void setCreationTime( java.util.Date creationTime ) ;

   /**
    * Returns the OPM model's description string.
    * @return the OPM model's description.
    */
   public java.lang.String getDescription(  ) ;

   /**
    * Sets the description
    * @param description the new description value
    */
   public void setDescription( java.lang.String description ) ;

   /**
    * Returns the id for the workgroup containing the OPM model.
    * @return the id for the workgroup containing the OPM model.
    */
   public java.lang.String getWorkgroupID(  ) ;

   /**
    * Sets the id for the workgroup containing the OPM model.
    * @param workgroupID the new workgroup id value.
    */
   public void setWorkgroupID( java.lang.String workgroupID ) ;

   /**
    * Returns the total accumulated time of collaborative work on the OPM model.
    * @return the total accumulated time.
    */
   public java.lang.Integer getTotalCollaborativeTime(  ) ;

   /**
    * Sets the total accumulated time of collaborative work on the OPM model.
    * @param totalCollaborativeTime the new total accumulated time value.
    */
   public void setTotalCollaborativeTime( java.lang.Integer totalCollaborativeTime ) ;

   /**
    * Returns an <code>EnhancedOpmModelValue</code> object. Contains all the cmp fields for the OPM model and a Collection of <code>Enhanced2OpmModelPermissionsValue</code> objects, satisfying the entity bean's primary key. Enhanced2OpmModelPermissionsValue objects contain all flat OpmModelPermission fields and a flat UserValue object.
    * @return the enhanced OPM model value object.
    */
   public org.objectprocess.cmp.EnhancedOpmModelValue getEnhancedOpmModelValue(  ) ;

   /**
    * Returns an <code>OpmModelRevisionValue</code> object. Contains all the cmp fields for the OPM model, as well as a <code>Collection</code> of <code>MetaRevisionValue</code> objects containing meta data for all known revisions of the OPM model.
    * @return the OPM model revision value object.
    */
   public org.objectprocess.cmp.OpmModelRevisionsValue getOpmModelRevisionsValue(  ) ;

   /**
    * Returns an <code>OpmModelValue</code> object, contains all the cmp fields for the workgroup.
    * @return the OPM model value object.
    */
   public org.objectprocess.cmp.OpmModelValue getOpmModelValue(  ) ;

   /**
    * Returns an <code>UpdatableOpmModelValue</code> object, contains all cmp fields that can be updated.
    * @return the updatable OPM model value object.
    */
   public org.objectprocess.cmp.UpdatableOpmModelValue getUpdatableOpmModelValue(  ) ;

   /**
    * Returns an <code>EditableOpmModelValue</code> object, contains all cmp fields that can be initialized when creating the bean. This object should only be used as an argument for ejbCreate.
    * @return the editable OPM model value object.
    * @deprecated 
    */
   public org.objectprocess.cmp.EditableOpmModelValue getEditableOpmModelValue(  ) ;

   /**
    * Sets the updatable OPM model cmp fields.
    * @param updatableOpmModelValue the updated OPM model cmp fields.
    */
   public void setUpdatableOpmModelValue( org.objectprocess.cmp.UpdatableOpmModelValue updatableOpmModelValue ) ;

   /**
    * Sets the editable OPM model cmp fields, used only in ejbCreate.
    * @param editableOpmModelValue the new editable OPM model cmp fields.
    */
   public void setEditableOpmModelValue( org.objectprocess.cmp.EditableOpmModelValue editableOpmModelValue ) ;

}
