/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Remote interface for OpmModel.
 * @lomboz generated
 */
public interface OpmModel
   extends javax.ejb.EJBObject
{
   /**
    * Returns the OPM model's id
    * @return the OPM model's id
    */
   public java.lang.String getOpmModelID(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the OPM model's id
    * @param opmModelID the new OPM model's id value
    */
   public void setOpmModelID( java.lang.String opmModelID )
      throws java.rmi.RemoteException;

   /**
    * Returns the OPM model's name.
    * @return the OPM model's name.
    */
   public java.lang.String getOpmModelName(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the OPM model's name
    * @param opmModelName the new OPM model's name value
    */
   public void setOpmModelName( java.lang.String opmModelName )
      throws java.rmi.RemoteException;

   /**
    * Returns the OPM model's <code>enabled</code> flag value.
    * @return the OPM model's <code>enabled</code> flag value.
    */
   public java.lang.Boolean getEnabled(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the OPM model's <code>enabled</code> flag value.
    * @param enabled the new <code>enabled</code> flag value.
    */
   public void setEnabled( java.lang.Boolean enabled )
      throws java.rmi.RemoteException;

   /**
    * Returns the time the OPM model was created.
    * @return the time the OPM model was created.
    */
   public java.util.Date getCreationTime(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the time for OPM model creation. Initialized once, on <code>ejbCreate</code>.
    * @param CreationTime the new timestamp value
    */
   public void setCreationTime( java.util.Date creationTime )
      throws java.rmi.RemoteException;

   /**
    * Returns the OPM model's description string.
    * @return the OPM model's description.
    */
   public java.lang.String getDescription(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the description
    * @param description the new description value
    */
   public void setDescription( java.lang.String description )
      throws java.rmi.RemoteException;

   /**
    * Returns the id for the workgroup containing the OPM model.
    * @return the id for the workgroup containing the OPM model.
    */
   public java.lang.String getWorkgroupID(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the id for the workgroup containing the OPM model.
    * @param workgroupID the new workgroup id value.
    */
   public void setWorkgroupID( java.lang.String workgroupID )
      throws java.rmi.RemoteException;

   /**
    * Returns the total accumulated time of collaborative work on the OPM model.
    * @return the total accumulated time.
    */
   public java.lang.Integer getTotalCollaborativeTime(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the total accumulated time of collaborative work on the OPM model.
    * @param totalCollaborativeTime the new total accumulated time value.
    */
   public void setTotalCollaborativeTime( java.lang.Integer totalCollaborativeTime )
      throws java.rmi.RemoteException;

   /**
    * Returns an <code>EnhancedOpmModelValue</code> object. Contains all the cmp fields for the OPM model and a Collection of <code>Enhanced2OpmModelPermissionsValue</code> objects, satisfying the entity bean's primary key. Enhanced2OpmModelPermissionsValue objects contain all flat OpmModelPermission fields and a flat UserValue object.
    * @return the enhanced OPM model value object.
    */
   public org.objectprocess.cmp.EnhancedOpmModelValue getEnhancedOpmModelValue(  )
      throws java.rmi.RemoteException;

   /**
    * Returns an <code>OpmModelRevisionValue</code> object. Contains all the cmp fields for the OPM model, as well as a <code>Collection</code> of <code>MetaRevisionValue</code> objects containing meta data for all known revisions of the OPM model.
    * @return the OPM model revision value object.
    */
   public org.objectprocess.cmp.OpmModelRevisionsValue getOpmModelRevisionsValue(  )
      throws java.rmi.RemoteException;

   /**
    * Returns an <code>OpmModelValue</code> object, contains all the cmp fields for the workgroup.
    * @return the OPM model value object.
    */
   public org.objectprocess.cmp.OpmModelValue getOpmModelValue(  )
      throws java.rmi.RemoteException;

   /**
    * Returns an <code>UpdatableOpmModelValue</code> object, contains all cmp fields that can be updated.
    * @return the updatable OPM model value object.
    */
   public org.objectprocess.cmp.UpdatableOpmModelValue getUpdatableOpmModelValue(  )
      throws java.rmi.RemoteException;

   /**
    * Returns an <code>EditableOpmModelValue</code> object, contains all cmp fields that can be initialized when creating the bean. This object should only be used as an argument for ejbCreate.
    * @return the editable OPM model value object.
    * @deprecated 
    */
   public org.objectprocess.cmp.EditableOpmModelValue getEditableOpmModelValue(  )
      throws java.rmi.RemoteException;

}
