/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Remote interface for OpmModelPermissions.
 * @lomboz generated
 */
public interface OpmModelPermissions
   extends javax.ejb.EJBObject
{
   /**
    * Returns the opmModelID
    * @return the opmModelID
    */
   public java.lang.String getOpmModelID(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the opmModelID
    * @param java.lang.Integer the new opmModelID value
    */
   public void setOpmModelID( java.lang.String opmModelID )
      throws java.rmi.RemoteException;

   /**
    * Returns the userID
    * @return the userID
    */
   public java.lang.String getUserID(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the userID
    * @param java.lang.Integer the new userID value
    */
   public void setUserID( java.lang.String userID )
      throws java.rmi.RemoteException;

   /**
    * Returns the joinTime
    * @return the joinTime
    */
   public java.util.Date getJoinTime(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the joinTime
    * @param java.util.Date the new joinTime value
    */
   public void setJoinTime( java.util.Date joinTime )
      throws java.rmi.RemoteException;

   /**
    * Returns the accessControl
    * @return the accessControl
    */
   public java.lang.Integer getAccessControl(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the accessControl
    * @param java.lang.Integer the new accessControl value
    */
   public void setAccessControl( java.lang.Integer accessControl )
      throws java.rmi.RemoteException;

}
