/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Local interface for OpmModelPermissions.
 * @lomboz generated
 */
public interface OpmModelPermissionsLocal
   extends javax.ejb.EJBLocalObject
{

   public org.objectprocess.cmp.OpmModelLocal getOpmModel(  ) ;

   public void setOpmModel( org.objectprocess.cmp.OpmModelLocal OpmModel ) ;

   public org.objectprocess.cmp.UserLocal getUser(  ) ;

   public void setUser( org.objectprocess.cmp.UserLocal user ) ;

   /**
    * Returns the opmModelID
    * @return the opmModelID
    */
   public java.lang.String getOpmModelID(  ) ;

   /**
    * Sets the opmModelID
    * @param java.lang.Integer the new opmModelID value
    */
   public void setOpmModelID( java.lang.String opmModelID ) ;

   /**
    * Returns the userID
    * @return the userID
    */
   public java.lang.String getUserID(  ) ;

   /**
    * Sets the userID
    * @param java.lang.Integer the new userID value
    */
   public void setUserID( java.lang.String userID ) ;

   /**
    * Returns the joinTime
    * @return the joinTime
    */
   public java.util.Date getJoinTime(  ) ;

   /**
    * Sets the joinTime
    * @param java.util.Date the new joinTime value
    */
   public void setJoinTime( java.util.Date joinTime ) ;

   /**
    * Returns the accessControl
    * @return the accessControl
    */
   public java.lang.Integer getAccessControl(  ) ;

   /**
    * Sets the accessControl
    * @param java.lang.Integer the new accessControl value
    */
   public void setAccessControl( java.lang.Integer accessControl ) ;

   public void setOpmModelPermissions( org.objectprocess.cmp.EditableOpmModelPermissionsValue editableOpmModelPermissionsValue ) ;

   public org.objectprocess.cmp.EnhancedOpmModelPermissionsValue getEnhancedOpmModelPermissionsValue(  ) ;

   public org.objectprocess.cmp.Enhanced2OpmModelPermissionsValue getEnhanced2OpmModelPermissionsValue(  ) ;

   public org.objectprocess.cmp.OpmModelPermissionsValue getOpmModelPermissionsValue(  ) ;

   public org.objectprocess.cmp.EditableOpmModelPermissionsValue getEditableOpmModelPermissionsValue(  ) ;

}
