/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Value object for OpmModel.
 *
 * @lomboz generated
 */
public class OpmModelRevisionsValue
   extends java.lang.Object
   implements java.io.Serializable 
{
   private java.lang.String opmModelID;
   private boolean opmModelIDHasBeenSet = false;
   private java.lang.String opmModelName;
   private boolean opmModelNameHasBeenSet = false;
   private java.lang.Boolean enabled;
   private boolean enabledHasBeenSet = false;
   private java.util.Date creationTime;
   private boolean creationTimeHasBeenSet = false;
   private java.lang.String description;
   private boolean descriptionHasBeenSet = false;
   private java.lang.String workgroupID;
   private boolean workgroupIDHasBeenSet = false;
   private java.lang.Integer totalCollaborativeTime;
   private boolean totalCollaborativeTimeHasBeenSet = false;
   private java.util.Collection OpmModelRevisions = new java.util.ArrayList();

   private java.lang.String pk;

   public OpmModelRevisionsValue()
   {
   }

   public OpmModelRevisionsValue( java.lang.String opmModelID,java.lang.String opmModelName,java.lang.Boolean enabled,java.util.Date creationTime,java.lang.String description,java.lang.String workgroupID,java.lang.Integer totalCollaborativeTime )
   {
	  this.opmModelID = opmModelID;
	  opmModelIDHasBeenSet = true;
	  this.opmModelName = opmModelName;
	  opmModelNameHasBeenSet = true;
	  this.enabled = enabled;
	  enabledHasBeenSet = true;
	  this.creationTime = creationTime;
	  creationTimeHasBeenSet = true;
	  this.description = description;
	  descriptionHasBeenSet = true;
	  this.workgroupID = workgroupID;
	  workgroupIDHasBeenSet = true;
	  this.totalCollaborativeTime = totalCollaborativeTime;
	  totalCollaborativeTimeHasBeenSet = true;
	  pk = this.getOpmModelID();
   }

   //TODO Cloneable is better than this !
   public OpmModelRevisionsValue( OpmModelRevisionsValue otherValue )
   {
	  this.opmModelID = otherValue.opmModelID;
	  opmModelIDHasBeenSet = true;
	  this.opmModelName = otherValue.opmModelName;
	  opmModelNameHasBeenSet = true;
	  this.enabled = otherValue.enabled;
	  enabledHasBeenSet = true;
	  this.creationTime = otherValue.creationTime;
	  creationTimeHasBeenSet = true;
	  this.description = otherValue.description;
	  descriptionHasBeenSet = true;
	  this.workgroupID = otherValue.workgroupID;
	  workgroupIDHasBeenSet = true;
	  this.totalCollaborativeTime = otherValue.totalCollaborativeTime;
	  totalCollaborativeTimeHasBeenSet = true;
	// TODO Clone is better no ?
	  this.OpmModelRevisions = otherValue.OpmModelRevisions;

	  pk = this.getOpmModelID();
   }

   public java.lang.String getPrimaryKey()
   {
	  return pk;
   }

   public void setPrimaryKey( java.lang.String pk )
   {
      // it's also nice to update PK object - just in case
      // somebody would ask for it later...
      this.pk = pk;
	  setOpmModelID( pk );
   }

   public java.lang.String getOpmModelID()
   {
	  return this.opmModelID;
   }

   public void setOpmModelID( java.lang.String opmModelID )
   {
	  this.opmModelID = opmModelID;
	  opmModelIDHasBeenSet = true;

		  pk = opmModelID;
   }

   public boolean opmModelIDHasBeenSet(){
	  return opmModelIDHasBeenSet;
   }
   public java.lang.String getOpmModelName()
   {
	  return this.opmModelName;
   }

   public void setOpmModelName( java.lang.String opmModelName )
   {
	  this.opmModelName = opmModelName;
	  opmModelNameHasBeenSet = true;

   }

   public boolean opmModelNameHasBeenSet(){
	  return opmModelNameHasBeenSet;
   }
   public java.lang.Boolean getEnabled()
   {
	  return this.enabled;
   }

   public void setEnabled( java.lang.Boolean enabled )
   {
	  this.enabled = enabled;
	  enabledHasBeenSet = true;

   }

   public boolean enabledHasBeenSet(){
	  return enabledHasBeenSet;
   }
   public java.util.Date getCreationTime()
   {
	  return this.creationTime;
   }

   public void setCreationTime( java.util.Date creationTime )
   {
	  this.creationTime = creationTime;
	  creationTimeHasBeenSet = true;

   }

   public boolean creationTimeHasBeenSet(){
	  return creationTimeHasBeenSet;
   }
   public java.lang.String getDescription()
   {
	  return this.description;
   }

   public void setDescription( java.lang.String description )
   {
	  this.description = description;
	  descriptionHasBeenSet = true;

   }

   public boolean descriptionHasBeenSet(){
	  return descriptionHasBeenSet;
   }
   public java.lang.String getWorkgroupID()
   {
	  return this.workgroupID;
   }

   public void setWorkgroupID( java.lang.String workgroupID )
   {
	  this.workgroupID = workgroupID;
	  workgroupIDHasBeenSet = true;

   }

   public boolean workgroupIDHasBeenSet(){
	  return workgroupIDHasBeenSet;
   }
   public java.lang.Integer getTotalCollaborativeTime()
   {
	  return this.totalCollaborativeTime;
   }

   public void setTotalCollaborativeTime( java.lang.Integer totalCollaborativeTime )
   {
	  this.totalCollaborativeTime = totalCollaborativeTime;
	  totalCollaborativeTimeHasBeenSet = true;

   }

   public boolean totalCollaborativeTimeHasBeenSet(){
	  return totalCollaborativeTimeHasBeenSet;
   }

   protected java.util.Collection addedOpmModelRevisions = new java.util.ArrayList();
   protected java.util.Collection onceAddedOpmModelRevisions = new java.util.ArrayList();
   protected java.util.Collection removedOpmModelRevisions = new java.util.ArrayList();
   protected java.util.Collection updatedOpmModelRevisions = new java.util.ArrayList();

   public java.util.Collection getAddedOpmModelRevisions() { return addedOpmModelRevisions; }
   public java.util.Collection getOnceAddedOpmModelRevisions() { return onceAddedOpmModelRevisions; }
   public java.util.Collection getRemovedOpmModelRevisions() { return removedOpmModelRevisions; }
   public java.util.Collection getUpdatedOpmModelRevisions() { return updatedOpmModelRevisions; }

   public void setAddedOpmModelRevisions(java.util.Collection addedOpmModelRevisions)
   {
      this.addedOpmModelRevisions.clear();
      this.addedOpmModelRevisions.addAll(addedOpmModelRevisions);
   }

   public void setOnceAddedOpmModelRevisions(java.util.Collection onceAddedOpmModelRevisions)
   {
      this.onceAddedOpmModelRevisions.clear();
      this.onceAddedOpmModelRevisions.addAll(onceAddedOpmModelRevisions);
   }

   public void setRemovedOpmModelRevisions(java.util.Collection removedOpmModelRevisions)
   {
      this.removedOpmModelRevisions.clear();
      this.removedOpmModelRevisions.addAll(removedOpmModelRevisions);
   }

   public void setUpdatedOpmModelRevisions(java.util.Collection updatedOpmModelRevisions)
   {
      this.updatedOpmModelRevisions.clear();
      this.updatedOpmModelRevisions.addAll(updatedOpmModelRevisions);
   }

   public org.objectprocess.cmp.MetaRevisionValue[] getOpmModelRevisions()
   {
	  return (org.objectprocess.cmp.MetaRevisionValue[])this.OpmModelRevisions.toArray(new org.objectprocess.cmp.MetaRevisionValue[OpmModelRevisions.size()]);
   }

   public void setOpmModelRevisions(org.objectprocess.cmp.MetaRevisionValue[] OpmModelRevisions)
   {
      this.OpmModelRevisions.clear();
      for (int i=0; i < OpmModelRevisions.length; i++)
      	this.OpmModelRevisions.add(OpmModelRevisions[i]);
   }

   public void clearOpmModelRevisions()
   {
	  this.OpmModelRevisions.clear();
   }

   public void addOpmModelRevision(org.objectprocess.cmp.MetaRevisionValue added)
   {
	  this.OpmModelRevisions.add(added);

      if (this.removedOpmModelRevisions.contains(added))
      {
        this.removedOpmModelRevisions.remove(added);
        if (this.onceAddedOpmModelRevisions.contains(added))
        {
          if (! this.addedOpmModelRevisions.contains(added))
            this.addedOpmModelRevisions.add(added);
        }
        else if (! this.updatedOpmModelRevisions.contains(added))
        {
            this.updatedOpmModelRevisions.add(added);
        }
      }
      else
      {
        if (! this.onceAddedOpmModelRevisions.contains(added))
          this.onceAddedOpmModelRevisions.add(added);
        if (! this.addedOpmModelRevisions.contains(added))
          this.addedOpmModelRevisions.add(added);
      }
   }

   public void removeOpmModelRevision(org.objectprocess.cmp.MetaRevisionValue removed)
   {
	  this.OpmModelRevisions.remove(removed);

      if (this.addedOpmModelRevisions.contains(removed))
        this.addedOpmModelRevisions.remove(removed);
      else if (! this.removedOpmModelRevisions.contains(removed))
        this.removedOpmModelRevisions.add(removed);

	  if (this.updatedOpmModelRevisions.contains(removed))
		 this.updatedOpmModelRevisions.remove(removed);
   }

   public void updateOpmModelRevision(org.objectprocess.cmp.MetaRevisionValue updated)
   {
	  if ( !this.updatedOpmModelRevisions.contains(updated) && !this.addedOpmModelRevisions.contains(updated))
		 this.updatedOpmModelRevisions.add(updated);
      if (this.removedOpmModelRevisions.contains(updated))
         this.removedOpmModelRevisions.remove(updated);
   }

   public void cleanOpmModelRevision(){
	  this.addedOpmModelRevisions = new java.util.ArrayList();
      this.onceAddedOpmModelRevisions = new java.util.ArrayList();
	  this.removedOpmModelRevisions = new java.util.ArrayList();
	  this.updatedOpmModelRevisions = new java.util.ArrayList();
   }

   public void copyOpmModelRevisionsFrom(org.objectprocess.cmp.OpmModelRevisionsValue from)
   {
	  // TODO Clone the List ????
	  this.OpmModelRevisions = from.OpmModelRevisions;
   }

   public String toString()
   {
	  StringBuffer str = new StringBuffer("{");

	  str.append("opmModelID=" + getOpmModelID() + " " + "opmModelName=" + getOpmModelName() + " " + "enabled=" + getEnabled() + " " + "creationTime=" + getCreationTime() + " " + "description=" + getDescription() + " " + "workgroupID=" + getWorkgroupID() + " " + "totalCollaborativeTime=" + getTotalCollaborativeTime());
	  str.append('}');

	  return(str.toString());
   }

   /**
    * A Value Object has an identity if the attributes making its Primary Key have all been set. An object without identity is never equal to any other object.
    *
    * @return true if this instance has an identity.
    */
   protected boolean hasIdentity()
   {
	  return opmModelIDHasBeenSet;
   }

   public boolean equals(Object other)
   {
      if (this == other)
         return true;
	  if ( ! hasIdentity() ) return false;
	  if (other instanceof OpmModelRevisionsValue)
	  {
		 OpmModelRevisionsValue that = (OpmModelRevisionsValue) other;
		 if ( ! that.hasIdentity() ) return false;
		 boolean lEquals = true;
		 if( this.opmModelID == null )
		 {
			lEquals = lEquals && ( that.opmModelID == null );
		 }
		 else
		 {
			lEquals = lEquals && this.opmModelID.equals( that.opmModelID );
		 }

		 lEquals = lEquals && isIdentical(that);

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public boolean isIdentical(Object other)
   {
	  if (other instanceof OpmModelRevisionsValue)
	  {
		 OpmModelRevisionsValue that = (OpmModelRevisionsValue) other;
		 boolean lEquals = true;
		 if( this.opmModelName == null )
		 {
			lEquals = lEquals && ( that.opmModelName == null );
		 }
		 else
		 {
			lEquals = lEquals && this.opmModelName.equals( that.opmModelName );
		 }
		 if( this.enabled == null )
		 {
			lEquals = lEquals && ( that.enabled == null );
		 }
		 else
		 {
			lEquals = lEquals && this.enabled.equals( that.enabled );
		 }
		 if( this.creationTime == null )
		 {
			lEquals = lEquals && ( that.creationTime == null );
		 }
		 else
		 {
			lEquals = lEquals && this.creationTime.equals( that.creationTime );
		 }
		 if( this.description == null )
		 {
			lEquals = lEquals && ( that.description == null );
		 }
		 else
		 {
			lEquals = lEquals && this.description.equals( that.description );
		 }
		 if( this.workgroupID == null )
		 {
			lEquals = lEquals && ( that.workgroupID == null );
		 }
		 else
		 {
			lEquals = lEquals && this.workgroupID.equals( that.workgroupID );
		 }
		 if( this.totalCollaborativeTime == null )
		 {
			lEquals = lEquals && ( that.totalCollaborativeTime == null );
		 }
		 else
		 {
			lEquals = lEquals && this.totalCollaborativeTime.equals( that.totalCollaborativeTime );
		 }
		 if( this.getOpmModelRevisions() == null )
		 {
			lEquals = lEquals && ( that.getOpmModelRevisions() == null );
		 }
		 else
		 {
			lEquals = lEquals && java.util.Arrays.equals(this.getOpmModelRevisions() , that.getOpmModelRevisions()) ;
		 }

		 return lEquals;
	  }
	  else
	  {
		 return false;
	  }
   }

   public int hashCode(){
	  int result = 17;
      result = 37*result + ((this.opmModelID != null) ? this.opmModelID.hashCode() : 0);

      result = 37*result + ((this.opmModelName != null) ? this.opmModelName.hashCode() : 0);

      result = 37*result + ((this.enabled != null) ? this.enabled.hashCode() : 0);

      result = 37*result + ((this.creationTime != null) ? this.creationTime.hashCode() : 0);

      result = 37*result + ((this.description != null) ? this.description.hashCode() : 0);

      result = 37*result + ((this.workgroupID != null) ? this.workgroupID.hashCode() : 0);

      result = 37*result + ((this.totalCollaborativeTime != null) ? this.totalCollaborativeTime.hashCode() : 0);

	  result = 37*result + ((this.getOpmModelRevisions() != null) ? this.getOpmModelRevisions().hashCode() : 0);
	  return result;
   }

}
