/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Home interface for OpmModelPermissions.
 * @lomboz generated
 */
public interface OpmModelPermissionsHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/OpmModelPermissions";
   public static final String JNDI_NAME="OpmModelPermissionsBean";

   public org.objectprocess.cmp.OpmModelPermissions create(org.objectprocess.cmp.EditableOpmModelPermissionsValue editableOpmModelPermissionsValue)
      throws javax.ejb.CreateException,java.rmi.RemoteException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public org.objectprocess.cmp.OpmModelPermissions findByPrimaryKey(org.objectprocess.cmp.OpmModelPermissionsPK pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
