/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * CMP layer for OpmModelPermissions.
 * @lomboz generated
 */
public abstract class OpmModelPermissionsCMP
   extends org.objectprocess.cmp.OpmModelPermissionsBean
   implements javax.ejb.EntityBean
{

   /**
    * Generated ejbPostCreate for corresponding ejbCreate method.
    *
    * @see #ejbCreate(org.objectprocess.cmp.EditableOpmModelPermissionsValue editableOpmModelPermissionsValue)
    */
   public void ejbPostCreate(org.objectprocess.cmp.EditableOpmModelPermissionsValue editableOpmModelPermissionsValue)
   {
   }

   public void ejbLoad() 
   {
   }

   public void ejbStore() 
   {
   }

   public void ejbActivate() 
   {
   }

   public void ejbPassivate() 
   {

      EnhancedOpmModelPermissionsValue = null;
      Enhanced2OpmModelPermissionsValue = null;
      OpmModelPermissionsValue = null;
      EditableOpmModelPermissionsValue = null;
   }

   public void setEntityContext(javax.ejb.EntityContext ctx) 
   {
   }

   public void unsetEntityContext() 
   {
   }

   public void ejbRemove() throws javax.ejb.RemoveException
   {

   }

 /* Value Objects BEGIN */

   private org.objectprocess.cmp.EnhancedOpmModelPermissionsValue EnhancedOpmModelPermissionsValue = null;

   public org.objectprocess.cmp.EnhancedOpmModelPermissionsValue getEnhancedOpmModelPermissionsValue()
   {
      EnhancedOpmModelPermissionsValue = new org.objectprocess.cmp.EnhancedOpmModelPermissionsValue();
      try
         {
            EnhancedOpmModelPermissionsValue.setOpmModelID( getOpmModelID() );
            EnhancedOpmModelPermissionsValue.setUserID( getUserID() );
            EnhancedOpmModelPermissionsValue.setJoinTime( getJoinTime() );
            EnhancedOpmModelPermissionsValue.setAccessControl( getAccessControl() );
            if ( getOpmModel() != null )
               EnhancedOpmModelPermissionsValue.setOpmModel( getOpmModel().getOpmModelValue() );

         }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return EnhancedOpmModelPermissionsValue;
   }
   private org.objectprocess.cmp.Enhanced2OpmModelPermissionsValue Enhanced2OpmModelPermissionsValue = null;

   public org.objectprocess.cmp.Enhanced2OpmModelPermissionsValue getEnhanced2OpmModelPermissionsValue()
   {
      Enhanced2OpmModelPermissionsValue = new org.objectprocess.cmp.Enhanced2OpmModelPermissionsValue();
      try
         {
            Enhanced2OpmModelPermissionsValue.setOpmModelID( getOpmModelID() );
            Enhanced2OpmModelPermissionsValue.setUserID( getUserID() );
            Enhanced2OpmModelPermissionsValue.setJoinTime( getJoinTime() );
            Enhanced2OpmModelPermissionsValue.setAccessControl( getAccessControl() );
            if ( getUser() != null )
               Enhanced2OpmModelPermissionsValue.setUser( getUser().getUserValue() );

         }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return Enhanced2OpmModelPermissionsValue;
   }
   private org.objectprocess.cmp.OpmModelPermissionsValue OpmModelPermissionsValue = null;

   public org.objectprocess.cmp.OpmModelPermissionsValue getOpmModelPermissionsValue()
   {
      OpmModelPermissionsValue = new org.objectprocess.cmp.OpmModelPermissionsValue();
      try
         {
            OpmModelPermissionsValue.setOpmModelID( getOpmModelID() );
            OpmModelPermissionsValue.setUserID( getUserID() );
            OpmModelPermissionsValue.setJoinTime( getJoinTime() );
            OpmModelPermissionsValue.setAccessControl( getAccessControl() );

         }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return OpmModelPermissionsValue;
   }
   private org.objectprocess.cmp.EditableOpmModelPermissionsValue EditableOpmModelPermissionsValue = null;

   public org.objectprocess.cmp.EditableOpmModelPermissionsValue getEditableOpmModelPermissionsValue()
   {
      EditableOpmModelPermissionsValue = new org.objectprocess.cmp.EditableOpmModelPermissionsValue();
      try
         {
            EditableOpmModelPermissionsValue.setOpmModelID( getOpmModelID() );
            EditableOpmModelPermissionsValue.setUserID( getUserID() );
            EditableOpmModelPermissionsValue.setAccessControl( getAccessControl() );

         }
         catch (Exception e)
         {
            throw new javax.ejb.EJBException(e);
         }

	  return EditableOpmModelPermissionsValue;
   }

/* Value Objects END */

   public abstract java.lang.String getOpmModelID() ;

   public abstract void setOpmModelID( java.lang.String opmModelID ) ;

   public abstract java.lang.String getUserID() ;

   public abstract void setUserID( java.lang.String userID ) ;

   public abstract java.util.Date getJoinTime() ;

   public abstract void setJoinTime( java.util.Date joinTime ) ;

   public abstract java.lang.Integer getAccessControl() ;

   public abstract void setAccessControl( java.lang.Integer accessControl ) ;

}
