/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Primary key for OpmModelPermissions.
 * @lomboz generated
 */
public class OpmModelPermissionsPK
   extends java.lang.Object
   implements java.io.Serializable
{

   public java.lang.String opmModelID;
   public java.lang.String userID;

   public OpmModelPermissionsPK()
   {
   }

   public OpmModelPermissionsPK( java.lang.String opmModelID,java.lang.String userID )
   {
      this.opmModelID = opmModelID;
      this.userID = userID;
   }

   public java.lang.String getOpmModelID()
   {
      return opmModelID;
   }
   public java.lang.String getUserID()
   {
      return userID;
   }

   public void setOpmModelID(java.lang.String opmModelID)
   {
      this.opmModelID = opmModelID;
   }
   public void setUserID(java.lang.String userID)
   {
      this.userID = userID;
   }

   public int hashCode()
   {
      int _hashCode = 0;
         if (this.opmModelID != null) _hashCode += this.opmModelID.hashCode();
         if (this.userID != null) _hashCode += this.userID.hashCode();

      return _hashCode;
   }

   public boolean equals(Object obj)
   {
      if( !(obj instanceof org.objectprocess.cmp.OpmModelPermissionsPK) )
         return false;

      org.objectprocess.cmp.OpmModelPermissionsPK pk = (org.objectprocess.cmp.OpmModelPermissionsPK)obj;
      boolean eq = true;

      if( obj == null )
      {
         eq = false;
      }
      else
      {
         if( this.opmModelID != null )
         {
            eq = eq && this.opmModelID.equals( pk.getOpmModelID() );
         }
         else  // this.opmModelID == null
         {
            eq = eq && ( pk.getOpmModelID() == null );
         }
         if( this.userID != null )
         {
            eq = eq && this.userID.equals( pk.getUserID() );
         }
         else  // this.userID == null
         {
            eq = eq && ( pk.getUserID() == null );
         }
      }

      return eq;
   }

   /** @return String representation of this pk in the form of [.field1.field2.field3]. */
   public String toString()
   {
      StringBuffer toStringValue = new StringBuffer("[.");
         toStringValue.append(this.opmModelID).append('.');
         toStringValue.append(this.userID).append('.');
      toStringValue.append(']');
      return toStringValue.toString();
   }

}
