/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Home interface for Revision.
 * @lomboz generated
 */
public interface RevisionHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/Revision";
   public static final String JNDI_NAME="RevisionBean";

   public org.objectprocess.cmp.Revision create(org.objectprocess.cmp.EditableRevisionValue editableRevisionValue)
      throws javax.ejb.CreateException,java.rmi.RemoteException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public java.util.Collection findByCurrentRevision(java.lang.Integer build, java.lang.String opmModelID)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public java.util.Collection findByRevisionNumber(java.lang.Integer majorRevision, java.lang.Integer minorRevision, java.lang.String opmModelID)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public java.util.Collection findByOpmModelID(java.lang.String opmModelID)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public org.objectprocess.cmp.Revision findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
