/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Local home interface for Revision.
 * @lomboz generated
 */
public interface RevisionLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/RevisionLocal";
   public static final String JNDI_NAME="RevisionLocal";

   public org.objectprocess.cmp.RevisionLocal create(org.objectprocess.cmp.EditableRevisionValue editableRevisionValue)
      throws javax.ejb.CreateException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public java.util.Collection findByCurrentRevision(java.lang.Integer build, java.lang.String opmModelID)
      throws javax.ejb.FinderException;

   public java.util.Collection findByRevisionNumber(java.lang.Integer majorRevision, java.lang.Integer minorRevision, java.lang.String opmModelID)
      throws javax.ejb.FinderException;

   public java.util.Collection findByOpmModelID(java.lang.String opmModelID)
      throws javax.ejb.FinderException;

   public org.objectprocess.cmp.RevisionLocal findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException;

}
