/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Local interface for Revision.
 * @lomboz generated
 */
public interface RevisionLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Returns an <code>OpmModelLocal</code> the revision is based on.
    * @return the <code>OpmModelLocal</code>.
    */
   public org.objectprocess.cmp.OpmModelLocal getOpmModel(  ) ;

   public void setOpmModel( org.objectprocess.cmp.OpmModelLocal OpmModel ) ;

   /**
    * Returns the revision's id.
    * @return the revision's id.
    */
   public java.lang.String getRevisionID(  ) ;

   /**
    * Sets the revision's id.
    * @param revisionID the new revision id value.
    */
   public void setRevisionID( java.lang.String revisionID ) ;

   /**
    * Returns the id for the OPM model the revision is based on.
    * @return the OPM model's id.
    */
   public java.lang.String getOpmModelID(  ) ;

   /**
    * Sets the id of the OPM model the revision is based on.
    * @param opmModelID the new OPM model id value.
    */
   public void setOpmModelID( java.lang.String opmModelID ) ;

   /**
    * Returns the OPX file of the revision.
    * @return the OPX file.
    */
   public java.lang.String getOpmModelFile(  ) ;

   /**
    * Sets the OPX file for the revision.
    * @param opmModelFile the new OPX file value.
    */
   public void setOpmModelFile( java.lang.String opmModelFile ) ;

   /**
    * Returns the revision's <code>enabled</code> flag value.
    * @return the enabled flag value.
    */
   public java.lang.Boolean getEnabled(  ) ;

   /**
    * Sets the revision's <code>enabled</code> flag value.
    * @param enabled the new <code>enabled</code> flag value.
    */
   public void setEnabled( java.lang.Boolean enabled ) ;

   /**
    * Returns the revision's major revision number.
    * @return the major revision number.
    */
   public java.lang.Integer getMajorRevision(  ) ;

   /**
    * Sets the revision's major revision number.
    * @param revision the new major revision number value.
    */
   public void setMajorRevision( java.lang.Integer revision ) ;

   /**
    * Returns the revision's minor revision number.
    * @return the minor revision number.
    */
   public java.lang.Integer getMinorRevision(  ) ;

   /**
    * Sets the revision's minor revision number.
    * @param revision the new minor revision value.
    */
   public void setMinorRevision( java.lang.Integer revision ) ;

   /**
    * Returns the revision's build number.
    * @return the build number.
    */
   public java.lang.Integer getBuild(  ) ;

   /**
    * Sets the revision's build number,
    * @param build the new build number value.
    */
   public void setBuild( java.lang.Integer build ) ;

   /**
    * Returns the creationTime
    * @return the creationTime
    */
   public java.util.Date getCreationTime(  ) ;

   /**
    * Sets the creationTime
    * @param creationTime the new creationTime value
    */
   public void setCreationTime( java.util.Date creationTime ) ;

   /**
    * Returns the comitterID
    * @return the comitterID
    */
   public java.lang.String getComitterID(  ) ;

   /**
    * Sets the comitterID
    * @param comitterID the new comitterID value
    */
   public void setComitterID( java.lang.String comitterID ) ;

   /**
    * Returns the description
    * @return the description
    */
   public java.lang.String getDescription(  ) ;

   /**
    * Sets the description
    * @param description the new description value
    */
   public void setDescription( java.lang.String description ) ;

   /**
    * Update the object with the Editable Value Object
    * @param editableRevisionValue the new Editable Revision fields
    */
   public void setEditableRevisionValue( org.objectprocess.cmp.EditableRevisionValue editableRevisionValue ) ;

   public org.objectprocess.cmp.FullRevisionValue getFullRevisionValue(  ) ;

   public org.objectprocess.cmp.EditableRevisionValue getEditableRevisionValue(  ) ;

   public org.objectprocess.cmp.MetaRevisionValue getMetaRevisionValue(  ) ;

}
