/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Local interface for User.
 * @lomboz generated
 */
public interface UserLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * returns a <code>Collection</code> of <code>WorkgroupPermissionsLocal</code> related to the user.
    * @return a collection of related <code>WorkgroupPermissionsLocal</code>.
    */
   public java.util.Collection getWorkgroupPermissions(  ) ;

   /**
    * sets the workgroup permissions for the user.
    * @param workgroupPermissions a collection of workgroup permission objects
    */
   public void setWorkgroupPermissions( java.util.Collection workgroupPermissions ) ;

   /**
    * returns a <code>Collection</code> of <code>OpmModelPermissionsLocal</code> related to the user.
    * @return a collection of related <code>OpmModelPermissionsLocal</code>.
    */
   public java.util.Collection getOpmModelPermissions(  ) ;

   /**
    * sets the OPM model permissions for the user
    * @param opmModelPermissions a collection of OPM model presmissions
    */
   public void setOpmModelPermissions( java.util.Collection opmModelPermissions ) ;

   /**
    * returns a <code>Collection</code> of <code>CollaborativeSessionPermissionsLocal</code> related to the user.
    * @return a collection of related <code>CollaborativeSessionPermissionsLocal</code>.
    */
   public java.util.Collection getCollaborativeSessionPermissions(  ) ;

   /**
    * sets the collaborative session permissions for the user
    * @param collaborativeSessionPermissions a collection of collaborative session permissions
    */
   public void setCollaborativeSessionPermissions( java.util.Collection collaborativeSessionPermissions ) ;

   /**
    * Returns the user's id.
    * @return the user's id.
    */
   public java.lang.String getUserID(  ) ;

   /**
    * Sets the user's id.
    * @param userID The new user id value.
    */
   public void setUserID( java.lang.String userID ) ;

   /**
    * Returns the user's login name.
    * @return the user's login name.
    */
   public java.lang.String getLoginName(  ) ;

   /**
    * Sets the user's login name.
    * @param loginName the new login name value.
    */
   public void setLoginName( java.lang.String loginName ) ;

   /**
    * Returns the user's first name.
    * @return the user's first name.
    */
   public java.lang.String getFirstName(  ) ;

   /**
    * Sets the user's first name.
    * @param firstName the new first name value.
    */
   public void setFirstName( java.lang.String firstName ) ;

   /**
    * Returns the user's last name.
    * @return the user's last name.
    */
   public java.lang.String getLastName(  ) ;

   /**
    * Sets the user's last name.
    * @param lastName the new last name value.
    */
   public void setLastName( java.lang.String lastName ) ;

   /**
    * Returns the user's password.
    * @return the user's password.
    */
   public java.lang.String getPassword(  ) ;

   /**
    * Sets the user's password.
    * @param password the new password value.
    */
   public void setPassword( java.lang.String password ) ;

   /**
    * Returns the user's email.
    * @return the user's email.
    */
   public java.lang.String getEmail(  ) ;

   /**
    * Sets the user's email.
    * @param email the new email value.
    */
   public void setEmail( java.lang.String email ) ;

   /**
    * Returns the user's <code>enabled</code> flag value, Setting to <code>false</code> will deny the user's login.
    * @return the user's <code>enabled</code> flag value.
    */
   public java.lang.Boolean getEnabled(  ) ;

   /**
    * Sets the user's <code>enabled</code> flag value.
    * @param enabled the new <code>enabled</code> flag value.
    */
   public void setEnabled( java.lang.Boolean enabled ) ;

   /**
    * Returns the user's <code>loggedIn</code> flag value.
    * @return the user's <code>loggedIn</code> flag value.
    */
   public java.lang.Boolean getLoggedIn(  ) ;

   /**
    * Sets the user's <code>loggedIn</code> flag value.
    * @param loggenIn the new <code>loggedIn</code> flag value.
    */
   public void setLoggedIn( java.lang.Boolean loggenIn ) ;

   /**
    * Returns the last time the user has logged in, updates every login.
    * @return the last time the user has logged in.
    */
   public java.util.Date getLastLoginTime(  ) ;

   /**
    * Sets the user's last login time stamp.
    * @param lastLoginTime the new login time value.
    */
   public void setLastLoginTime( java.util.Date lastLoginTime ) ;

   /**
    * Returns the user's description string.
    * @return the user's description.
    */
   public java.lang.String getDescription(  ) ;

   /**
    * Sets the user's description string.
    * @param description the new description value.
    */
   public void setDescription( java.lang.String description ) ;

   /**
    * Returns the <code>administrator</code> flag value.
    * @return the <code>administrator</code> flag value.
    */
   public java.lang.Boolean getAdministrator(  ) ;

   /**
    * Sets the <code>administrator</code> flag value.
    * @param administrator the new the <code>administrator</code> flag value.
    */
   public void setAdministrator( java.lang.Boolean administrator ) ;

   /**
    * Returns an <code>EnhancedUserValue</code> object. Contains all the cmp fields for the user, a Collection of <code>EnhancedWorkgroupPermissionValue</code> objects, a Collection of <code>EnhancedOpmModelPermissionValue</code> objects, and a Collection <code>of EnhancedCollaborativeSessionPermissionValue</code> objects, all satisfying the entity bean's primary key. each enhanced permission object contains the corresponding object. <p> for example: EnhancedWorkgroupPermissionValue objects contain a flat WorkgroupValue object. Useful for getting an entire tree of objects related to the user.
    * @return the enhanced user value object.
    */
   public org.objectprocess.cmp.EnhancedUserValue getEnhancedUserValue(  ) ;

   /**
    * Returns a <code>UserValue</code> object. Contains all the cmp fields for the user but the password.
    * @return the user value object.
    */
   public org.objectprocess.cmp.UserValue getUserValue(  ) ;

   /**
    * Returns an <code>UpdatableUserValue</code> object. Contains all cmp fields that can be updated.
    * @return the updatable user value object.
    */
   public org.objectprocess.cmp.UpdatableUserValue getUpdatableUserValue(  ) ;

   /**
    * Returns an <code>EditableUserValue</code> object. Contains all cmp fields that can be initialized when creating the bean. This object should only be used as an argument for ejbCreate.
    * @return the editable user value object.
    * @deprecated 
    */
   public org.objectprocess.cmp.EditableUserValue getEditableUserValue(  ) ;

   /**
    * Sets the updatable user cmp fields.
    * @param updatableUserValue the updated user cmp fields.
    */
   public void setUpdatableUserValue( org.objectprocess.cmp.UpdatableUserValue updatableUserValue ) ;

   /**
    * Sets the editable user cmp fields, used only in ejbCreate.
    * @param editableUserValue the new editable user cmp fields.
    */
   public void setEditableUserValue( org.objectprocess.cmp.EditableUserValue editableUserValue ) ;

}
