/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Local home interface for User.
 * @lomboz generated
 */
public interface UserLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/UserLocal";
   public static final String JNDI_NAME="UserLocal";

   public org.objectprocess.cmp.UserLocal create(org.objectprocess.cmp.EditableUserValue editableUserValue)
      throws javax.ejb.CreateException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public java.util.Collection findByLoginName(java.lang.String loginName)
      throws javax.ejb.FinderException;

   public org.objectprocess.cmp.UserLocal findByPrimaryKey(java.lang.String pk)
      throws javax.ejb.FinderException;

}
