/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Remote interface for Workgroup.
 * @lomboz generated
 */
public interface Workgroup
   extends javax.ejb.EJBObject
{
   /**
    * Returns the workgroup's id.
    * @return the workgroup's id.
    */
   public java.lang.String getWorkgroupID(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the workgroup's id.
    * @param workgroupID the new workgroupID value
    */
   public void setWorkgroupID( java.lang.String workgroupID )
      throws java.rmi.RemoteException;

   /**
    * Returns the workgroup's name.
    * @return the workgroup's name.
    */
   public java.lang.String getWorkgroupName(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the workgroup's name
    * @param workgroupName the new workgroup name value
    */
   public void setWorkgroupName( java.lang.String workgroupName )
      throws java.rmi.RemoteException;

   /**
    * Returns the workgroup's <code>enabled</code> flag value.
    * @return the workgroup's <code>enabled</code> flag value.
    */
   public java.lang.Boolean getEnabled(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the workgroup's <code>enabled</code> flag value.
    * @param enabled the new <code>enabled</code> flag value.
    */
   public void setEnabled( java.lang.Boolean enabled )
      throws java.rmi.RemoteException;

   /**
    * Returns the time the workgroup was created.
    * @return the time the workgroup was created.
    */
   public java.util.Date getCreationTime(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the time for workgroup creation. Initialized once, on <code>ejbCreate</code>.
    * @param CreationTime the new timestamp value
    */
   public void setCreationTime( java.util.Date creationTime )
      throws java.rmi.RemoteException;

   /**
    * Returns the workgroup's description string.
    * @return the workgroup's description.
    */
   public java.lang.String getDescription(  )
      throws java.rmi.RemoteException;

   /**
    * Sets the Description
    * @param Description the new Description value
    */
   public void setDescription( java.lang.String description )
      throws java.rmi.RemoteException;

}
