/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Local home interface for WorkgroupPermissions.
 * @lomboz generated
 */
public interface WorkgroupPermissionsLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/WorkgroupPermissionsLocal";
   public static final String JNDI_NAME="WorkgroupPermissionsLocal";

   public org.objectprocess.cmp.WorkgroupPermissionsLocal create(org.objectprocess.cmp.EditableWorkgroupPermissionsValue editableWorkgroupPermissionsValue)
      throws javax.ejb.CreateException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException;

   public org.objectprocess.cmp.WorkgroupPermissionsLocal findByPrimaryKey(org.objectprocess.cmp.WorkgroupPermissionsPK pk)
      throws javax.ejb.FinderException;

}
