/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Primary key for WorkgroupPermissions.
 * @lomboz generated
 */
public class WorkgroupPermissionsPK
   extends java.lang.Object
   implements java.io.Serializable
{

   public java.lang.String workgroupID;
   public java.lang.String userID;

   public WorkgroupPermissionsPK()
   {
   }

   public WorkgroupPermissionsPK( java.lang.String workgroupID,java.lang.String userID )
   {
      this.workgroupID = workgroupID;
      this.userID = userID;
   }

   public java.lang.String getWorkgroupID()
   {
      return workgroupID;
   }
   public java.lang.String getUserID()
   {
      return userID;
   }

   public void setWorkgroupID(java.lang.String workgroupID)
   {
      this.workgroupID = workgroupID;
   }
   public void setUserID(java.lang.String userID)
   {
      this.userID = userID;
   }

   public int hashCode()
   {
      int _hashCode = 0;
         if (this.workgroupID != null) _hashCode += this.workgroupID.hashCode();
         if (this.userID != null) _hashCode += this.userID.hashCode();

      return _hashCode;
   }

   public boolean equals(Object obj)
   {
      if( !(obj instanceof org.objectprocess.cmp.WorkgroupPermissionsPK) )
         return false;

      org.objectprocess.cmp.WorkgroupPermissionsPK pk = (org.objectprocess.cmp.WorkgroupPermissionsPK)obj;
      boolean eq = true;

      if( obj == null )
      {
         eq = false;
      }
      else
      {
         if( this.workgroupID != null )
         {
            eq = eq && this.workgroupID.equals( pk.getWorkgroupID() );
         }
         else  // this.workgroupID == null
         {
            eq = eq && ( pk.getWorkgroupID() == null );
         }
         if( this.userID != null )
         {
            eq = eq && this.userID.equals( pk.getUserID() );
         }
         else  // this.userID == null
         {
            eq = eq && ( pk.getUserID() == null );
         }
      }

      return eq;
   }

   /** @return String representation of this pk in the form of [.field1.field2.field3]. */
   public String toString()
   {
      StringBuffer toStringValue = new StringBuffer("[.");
         toStringValue.append(this.workgroupID).append('.');
         toStringValue.append(this.userID).append('.');
      toStringValue.append(']');
      return toStringValue.toString();
   }

}
