/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Home interface for WorkgroupPermissions.
 * @lomboz generated
 */
public interface WorkgroupPermissionsHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/WorkgroupPermissions";
   public static final String JNDI_NAME="WorkgroupPermissionsBean";

   public org.objectprocess.cmp.WorkgroupPermissions create(org.objectprocess.cmp.EditableWorkgroupPermissionsValue editableWorkgroupPermissionsValue)
      throws javax.ejb.CreateException,java.rmi.RemoteException;

   public java.util.Collection findAll()
      throws javax.ejb.FinderException,java.rmi.RemoteException;

   public org.objectprocess.cmp.WorkgroupPermissions findByPrimaryKey(org.objectprocess.cmp.WorkgroupPermissionsPK pk)
      throws javax.ejb.FinderException,java.rmi.RemoteException;

}
