/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Local interface for Workgroup.
 * @lomboz generated
 */
public interface WorkgroupLocal
   extends javax.ejb.EJBLocalObject
{
   /**
    * Returns a <code>Collection</code> of <code>WorkgroupPermissionsLocal</code> related to the workgroup.
    * @return a <code>Collection</code> of related <code>WorkgroupPermissionsLocal</code>.
    */
   public java.util.Collection getWorkgroupPermissions(  ) ;

   public void setWorkgroupPermissions( java.util.Collection workgroupPermissions ) ;

   /**
    * Returns a <code>Collection</code> of assosiated <code>OpmModelLocal</code>.
    * @return a <code>Collection</code> of assosiated <code>OpmModelLocal</code>.
    */
   public java.util.Collection getOpmModels(  ) ;

   public void setOpmModels( java.util.Collection opmModels ) ;

   /**
    * Returns the workgroup's id.
    * @return the workgroup's id.
    */
   public java.lang.String getWorkgroupID(  ) ;

   /**
    * Sets the workgroup's id.
    * @param workgroupID the new workgroupID value
    */
   public void setWorkgroupID( java.lang.String workgroupID ) ;

   /**
    * Returns the workgroup's name.
    * @return the workgroup's name.
    */
   public java.lang.String getWorkgroupName(  ) ;

   /**
    * Sets the workgroup's name
    * @param workgroupName the new workgroup name value
    */
   public void setWorkgroupName( java.lang.String workgroupName ) ;

   /**
    * Returns the workgroup's <code>enabled</code> flag value.
    * @return the workgroup's <code>enabled</code> flag value.
    */
   public java.lang.Boolean getEnabled(  ) ;

   /**
    * Sets the workgroup's <code>enabled</code> flag value.
    * @param enabled the new <code>enabled</code> flag value.
    */
   public void setEnabled( java.lang.Boolean enabled ) ;

   /**
    * Returns the time the workgroup was created.
    * @return the time the workgroup was created.
    */
   public java.util.Date getCreationTime(  ) ;

   /**
    * Sets the time for workgroup creation. Initialized once, on <code>ejbCreate</code>.
    * @param CreationTime the new timestamp value
    */
   public void setCreationTime( java.util.Date creationTime ) ;

   /**
    * Returns the workgroup's description string.
    * @return the workgroup's description.
    */
   public java.lang.String getDescription(  ) ;

   /**
    * Sets the Description
    * @param Description the new Description value
    */
   public void setDescription( java.lang.String description ) ;

   /**
    * Returns an <code>EnhancedWorkgroupValue</code> object. Contains all the cmp fields for the workgroup and a Collection of <code>Enhanced2WorkgroupPermissionValue</code> objects, satisfying the entity bean's primary key. Enhanced2WorkgroupPermissionValue objects contain all flat WorkgroupPermission fields and a flat UserValue object.
    * @return the enhanced workgroup value object.
    */
   public org.objectprocess.cmp.EnhancedWorkgroupValue getEnhancedWorkgroupValue(  ) ;

   /**
    * Returns a <code>WorkgroupValue</code> object, contains all the cmp fields for the workgroup.
    * @return the workgroup value object.
    */
   public org.objectprocess.cmp.WorkgroupValue getWorkgroupValue(  ) ;

   /**
    * Returns an <code>UpdatableWorkgroupValue</code> object, contains all cmp fields that can be updated.
    * @return the updatable workgroup value object.
    */
   public org.objectprocess.cmp.UpdatableWorkgroupValue getUpdatableWorkgroupValue(  ) ;

   /**
    * Returns an <code>EditableWorkgroupValue</code> object, contains all cmp fields that can be initialized when creating the bean. This object should only be used as an argument for ejbCreate.
    * @return the editable workgroup value object.
    * @deprecated 
    */
   public org.objectprocess.cmp.EditableWorkgroupValue getEditableWorkgroupValue(  ) ;

   /**
    * Sets the updatable workgroup cmp fields.
    * @param updatableWorkgroupValue the updated workgroup cmp fields.
    */
   public void setUpdatableWorkgroupValue( org.objectprocess.cmp.UpdatableWorkgroupValue updatableWorkgroupValue ) ;

   /**
    * Sets the editable workgroup cmp fields, used only in ejbCreate.
    * @param editableWorkgroupValue the new editable workgroup cmp fields.
    */
   public void setEditableWorkgroupValue( org.objectprocess.cmp.EditableWorkgroupValue editableWorkgroupValue ) ;

}
