/*
 * Generated by XDoclet - Do not edit!
 */
package org.objectprocess.cmp;

/**
 * Local interface for WorkgroupPermissions.
 * @lomboz generated
 */
public interface WorkgroupPermissionsLocal
   extends javax.ejb.EJBLocalObject
{

   public org.objectprocess.cmp.WorkgroupLocal getWorkgroup(  ) ;

   public void setWorkgroup( org.objectprocess.cmp.WorkgroupLocal workgroup ) ;

   public org.objectprocess.cmp.UserLocal getUser(  ) ;

   public void setUser( org.objectprocess.cmp.UserLocal user ) ;

   /**
    * Returns the workgroupID
    * @return the workgroupID
    */
   public java.lang.String getWorkgroupID(  ) ;

   /**
    * Sets the workgroupID
    * @param java.lang.Integer the new workgroupID value
    */
   public void setWorkgroupID( java.lang.String workgroupID ) ;

   /**
    * Returns the userID
    * @return the userID
    */
   public java.lang.String getUserID(  ) ;

   /**
    * Sets the userID
    * @param java.lang.Integer the new userID value
    */
   public void setUserID( java.lang.String userID ) ;

   /**
    * Returns the joinTime
    * @return the joinTime
    */
   public java.util.Date getJoinTime(  ) ;

   /**
    * Sets the joinTime
    * @param java.util.Date the new joinTime value
    */
   public void setJoinTime( java.util.Date joinTime ) ;

   /**
    * Returns the accessControl
    * @return the accessControl
    */
   public java.lang.Integer getAccessControl(  ) ;

   /**
    * Sets the accessControl
    * @param java.lang.Integer the new accessControl value
    */
   public void setAccessControl( java.lang.Integer accessControl ) ;

   public void setWorkgroupPermissions( org.objectprocess.cmp.EditableWorkgroupPermissionsValue editableWorkgroupPermissionsValue ) ;

   public org.objectprocess.cmp.EnhancedWorkgroupPermissionsValue getEnhancedWorkgroupPermissionsValue(  ) ;

   public org.objectprocess.cmp.Enhanced2WorkgroupPermissionsValue getEnhanced2WorkgroupPermissionsValue(  ) ;

   public org.objectprocess.cmp.WorkgroupPermissionsValue getWorkgroupPermissionsValue(  ) ;

   public org.objectprocess.cmp.EditableWorkgroupPermissionsValue getEditableWorkgroupPermissionsValue(  ) ;

}
